### ISSUE TITLE
Error 'WillNotConfigureFrontend' when trying to use managed certs + allow-http: false

### ISSUE THREAD

**Issue by dragonpaw** [kubernetes/ingress-gce#1001]
I'm trying to setup an API endpoint over https only, since I don't want to worry about data leakage over http (even with redirect to https, it isn't safe). 

Version: 1.15.7-gke.2 (Using GKE/GCP)

Ideal setup would look like:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-api
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: my-api-ip4
    networking.gke.io/managed-certificates: my-api.cert
spec:
  backend:
    serviceName: my-sv
    servicePort: 8000
```

Now, if I do this with the `allow-http` annotation missing, it does seem to provision both frontends correctly. (Once I add dns myself pointing to the IP, so that the cert will provision.) But doing so gives:
```sh
kubectl describe ingress my-api

[...]
Events:
  Type    Reason                    Age                  From                     Message
  ----    ------                    ----                 ----                     -------
  Normal  WillNotConfigureFrontend  9m17s (x2 over 10m)  loadbalancer-controller  Will not configure frontend based on Ingress specification. Please check your usage of the 'kubernetes.io/ingress.allow-http' annotation.
```

**Comment by cr8on** [comment]
I had the exact same issue... with pretty much the same YAML.

Resolved by adding my managed certificate name to 
`ingress.gcp.kubernetes.io/pre-shared-cert`

See https://github.com/kubernetes/ingress-gce/issues/738

**Comment by dragonpaw** [comment]
I can't see the workaround you mention in #738 

Something like:
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.gcp.kubernetes.io/pre-shared-cert: mcrt-[...]
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: my-ip4
```
?

**Comment by rramkumar1** [comment]
@dragonpaw Was the ManagedCertificate provisioned correctly? The controller for that API is supposed to add the cert name to the pre-shared-cert annotation automatically but it looks like that was not the case for you.

**Comment by cr8on** [comment]
@dragonpaw Maybe it was more implied in the other ticket. But yep, pretty much that. I kept the managed certificate annotation though. Didn't try it without that.

[Just a note that I am using the latest 1.14 version. Not 1.15 as the OP.]

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    networking.gke.io/managed-certificates: prod-ssl-cert
    ingress.gcp.kubernetes.io/pre-shared-cert: prod-ssl-cert
    etc...
```
