### ISSUE TITLE
Traefik behind GCP Load Balancer,

### ISSUE THREAD

**Issue by jbrunetext** [kubernetes/ingress-gce#1018]
Hello ,
I would like to config my Traefik behind my ingress-gce . 
i have created an ingress with TLS endpoint with GCP.

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tools-grafana-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: tools-lb-static-ip
    networking.gke.io/managed-certificates: grafana-tools-lb-managed-certificate
spec:
  rules:
    - host: {{ tpl (.Values.url) . }}
      http:
        paths:
          - path: /*
            backend:
              serviceName: tools-grafana
              servicePort: 80
```
Conform  to GCE ingres doc it's work, I  can natively auth my user with IAP through Ingress https://cloud.google.com/iap/docs/enabling-kubernetes-howto
but i would like proxy pass by internal load balancer 
in other word i would like to forward request to gce ingress to traefik proxy. All the trafic on url grafana.tools.XXXXXXX.cloud will be route to traefik ingress port 80

ingress
```
NAME                      HOSTS                                    ADDRESS        PORTS   AGE
gce-tools-grafana-ingress     grafana.tools.XXXXXXX.cloud   34.107.XX.XX  80      3h55m
traefik-grafana-ingress     grafana.tools.XXXXXXX.cloud                  80      3h55m
```

instead of reach directly the service  tools-grafana (Nodeport 80)
. i would like to reach my helm install of traefik (Nodeport 80 with backend Config IAP

```
tools-traefik   LoadBalancer   192.168.16.30   10.205.151.246   443:32577/TCP,80:32650/TCP
```
note my Loadbalancer is internal and get Internal IP address (Nodeport)
but i haven't found the annotation or example  in documentation  to implement this Scenario.
Traefik behind GCP Load Balancer with IAP
