### ISSUE TITLE
Add Hostname to HealthCheckConfig

### ISSUE THREAD

**Issue by tmc** [kubernetes/ingress-gce#1046]
Right now the HealthCheckConfig can't/doesn't allow specification of the Host header to send with the health check.

**Comment by mark-church** [comment]
Hi @tmc thanks for your question. We have not implemented this yet as we focused on configurability of the path first. Can you detail a little more on the use case for the host header in a health check and what kind of systems require this?

**Comment by tmc** [comment]
A use case is as follows:
If you service a health check from within a cluster with a VirtualService say with a VS like so:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
 name: healthcheck-virtualservice
spec:
 gateways:
   - foo-system/generic-gateway
 hosts:
   - healthcheck.foobar.com
 http:
   - match:
     - uri:
         exact: /
     rewrite:
       uri: /healthz/ready
     route:
     - destination:
         host: istio-ingressgateway.istio-system.svc.cluster.local
         port:
           number: 15020
```
If this healthcheck didn't have a specific hostname then the behavior of the cluster is surprising to developers/operators as the default request is then a content-free 200.

**Comment by mark-church** [comment]
Hi @tmc 

Does configuring the path of the GCE health check also solve the problem? It would be configured in the BackendConfig which will be supported soon by https://github.com/kubernetes/ingress-gce/pull/1040. Note that this PR does not support changing of the health check hostname, only path.

It could be done like this and referenced by the Service:

```
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: http-hc-config
spec:
  healthCheck:
    type: http
    requestPath: /healthz/ready
```

Then all hosts with `/healthz/ready` are matched and sent to the ingressgateway health check. 

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
 name: healthcheck-virtualservice
spec:
 gateways:
   - foo-system/generic-gateway
 hosts:
   - *
 http:
   - match:
     - uri:
         exact: /healthz/ready
     route:
     - destination:
         host: istio-ingressgateway.istio-system.svc.cluster.local
         port:
           number: 15020
```

Let me know if this has the same effect for you as changing the health check hostname.
