### ISSUE TITLE
Wrong health check with end-to-end https scheme

### ISSUE THREAD

**Issue by sdouche** [kubernetes/ingress-gce#105]
Hi,
I'm trying to set https end-to-end (GCP LB to K8S Pod). On the Pod I have gunicorn that doesn't support HTTP and HTTPS in the same time, but only one. So I must use HTTPS everywhere.

 I set this in the deployment object:
```
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /heartbeat/
            port: 443
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 10
```

I add this to the service object:
```
  annotations:
    service.alpha.kubernetes.io/app-protocols: '{"my-https-port":"HTTPS"}'
``` 

Unfortunately, the health check is set to check `/` on HTTP, and the backend service is on HTTP.

Note: The same configuration with HTTP works well (the LB is up and running).

Did I miss something?

Regards.

**Comment by pwistrand** [comment]
I've been having a similar issue over the last couple of days. Have you tried removing the readinessProbe from the deployment? I've witnessing that the GCE ingress doesn't pay any attention to it despite what the [documentation](https://github.com/kubernetes/ingress-gce#health-checks) says (especially as its still being discussed as a feature #42)

**Comment by nicksardo** [comment]
I can't reproduce. Post a simple reproducible manifest of the ingress/service/deployment. Make sure you're actually naming the port "my-https-port".

**Comment by sdouche** [comment]
Hi @nicksardo,
Apologize for the late reply. I use the same named port in service:
```
apiVersion: v1
kind: Service
metadata:
  name: booking
  namespace: booking
  annotations:
    service.alpha.kubernetes.io/app-protocols: '{"booking-port":"HTTPS"}'  
spec:
  type: NodePort
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: booking-port
  selector:
    app: booking
```
And ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: booking
  namespace: booking
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: booking
    service.alpha.kubernetes.io/app-protocols: '{"booking-port":"HTTPS"}' 
spec:
  tls:
  - hosts:
    - xxx
    secretName: booking
  rules:
  - host: xxx
    http:
      paths:
      - path: /*
        backend:
          serviceName: booking
          servicePort: booking-port
```

But I have this strange behavior:

![screenshot-20180205173347-413x68](https://user-images.githubusercontent.com/170176/35816660-93557c60-0a9b-11e8-849e-189dbbf0b022.png)
![screenshot-20180205173327-1048x496](https://user-images.githubusercontent.com/170176/35816661-9372fc2c-0a9b-11e8-9e03-b822ae72dd60.png)

Kubernertes says backends aren't healthy but the LB says they're goods.

But surprise after 5 minutes, it also good for k8s:
```ingress.kubernetes.io/backends: {"k8s-be-30656--d41670d42012045e":"HEALTHY","k8s-be-32505--d41670d42012045e":"HEALTHY"}```
