### ISSUE TITLE
HTTP to HTTPS redirection

### ISSUE THREAD

**Issue by Cyral** [kubernetes/ingress-gce#1075]
Now that GCP Load Balancers [finally have HTTP to HTTPS redirection support](https://issuetracker.google.com/issues/35904733#comment95), can this be configured through YAML so redirection is handled by GCP and not the application?

**Comment by mercuriete** [comment]
I think this is a duplicated of #51 
and not the other way round.

**Comment by rramkumar1** [comment]
cc @spencerhance who is working on integrating this into GKE Ingress.

**Comment by hypery2k** [comment]
any news on this?

**Comment by mark-church** [comment]
Yes we are currently working on this. It's currently in development so we don't have a committed timeline yet. We will update this thread as development gets closer to completion and we can provide a realistic estimate.

**Comment by thaniyarasu** [comment]
Can we get an approximate date for this fix into ingress-gce yaml

**Comment by mo4islona** [comment]
+1

**Comment by sp185503-ncr** [comment]
+1 this is really needed

**Comment by halradaideh** [comment]
@thaniyarasu can the GKE ingress have this feature ?

like annotation or something like that ?
to redirect from HTTP to HTTPS

**Comment by m-tanner** [comment]
+1

**Comment by dconvers1979** [comment]
+1

**Comment by clenn** [comment]
+1

**Comment by sp185503** [comment]
> @thaniyarasu can the GKE ingress have this feature ?
> 
> like annotation or something like that ?
> to redirect from HTTP to HTTPS

Ideally this would be the preferred way to use this feature, via annotation.

**Comment by mark-church** [comment]
Hi All, here's a quick update on where we stand with HTTPS redirects for GKE Ingress:

- It's still in development
- It will be implemented via a boolean enable/disable for the entire Ingress resource (using [FrontendConfig](https://godoc.org/k8s.io/ingress-gce/pkg/apis/frontendconfig/v1beta1) as a CRD to hold structured config for frontend load balancer policy)
- We're targeting Q3 for a release to GKE

**Comment by sp185503** [comment]
> Hi All, here's a quick update on where we stand with HTTPS redirects for GKE Ingress:
> 
> * It's still in development
> * It will be implemented via a boolean enable/disable for the entire Ingress resource (using [FrontendConfig](https://godoc.org/k8s.io/ingress-gce/pkg/apis/frontendconfig/v1beta1) as a CRD to hold structured config for frontend load balancer policy)
> * We're targeting Q3 for a release to GKE

Good to hear, thanks for sharing.

**Comment by m-tanner** [comment]
Just out of curiosity (not rushing!), will it be available towards the beginning or end of Q3?

**Comment by geun** [comment]
finally!! It's coming. I'm really waiting for this features.
[https://github.com/kubernetes/ingress-gce/pull/1206)](https://github.com/kubernetes/ingress-gce/pull/1206)

**Comment by icco** [comment]
Now that #1206 has been merged, what's the rollout process look like?

**Comment by spencerhance** [comment]
Hi @icco,

This should be rolling out to the GKE Rapid channel within the next two weeks.  It will be at least 2-3 weeks before you will see it in the GKE Regular channel.  I will post an update here as soon as we officially launch 🚀 .

**Comment by hadim** [comment]
That's great news.

How the redirection will be specified? In the `Ingress` spec within `metadata.annotations`? Something like this:

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app-remote-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: app-gcp-ip
    networking.gke.io/managed-certificates: app-certificate
    networking.gke.io/RedirectToHttps: PERMANENT_REDIRECT
spec:
  backend:
    serviceName: app-server-remote
    servicePort: 7777
```

**Comment by iagomelanias** [comment]
From #1206, it's possible to determine that the configuration is very similar to SSL Policies, as it uses the same resource kind `FrontendConfig`. @spencerhance explained how to use them [in this comment](https://github.com/kubernetes/ingress-gce/issues/246#issuecomment-617991794).

I imagine it would be something like this:
```yaml
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: test-frontend-config
spec:
  sslPolicy: ssl-policy-name
  redirectToHttps:
    enabled: true
    responseCodeName: PERMANENT_REDIRECT # possible values are: FOUND, TEMPORARY_REDIRECT, PERMANENT_REDIRECT, looks like the default is PERMANENT_REDIRECT
``` 

And the `Ingress` resource should have the following annotation.
```yaml
networking.gke.io/v1beta1.FrontendConfig: test-frontend-config
```

@spencerhance is it correct?

**Comment by ncoonrod** [comment]
@iagomelanias that ```redirectToHttps``` object isn't working for me on a GKE ```1.17.9-gke.6300``` cluster. I'm using networking.gke.io/v1beta1 as well. According to the docs at https://pkg.go.dev/k8s.io/ingress-gce/pkg/apis/frontendconfig/v1beta1
It looks like it should?

Here's how mine looks:
```
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: httpRedirect
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: PERMANENT_REDIRECT
```

When I try to deploy it, it says redirectToHttps doesn't exist.

**Comment by tvvignesh** [comment]
@spencerhance Any relation between GKE version and GCE ingress version? I have been looking at Rapid channel release notes since it is expected to arrive soon. But, not sure which version of GCE ingress is included with it. For instance, this was released 2 days ago and I am not able to see a release note for GCE ingress there: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#v1189 . Or did I miss something?

**Comment by GeckoSplinter** [comment]
Indeed It's hard to match the ingress-GCE version with a GKE version.

My point of reference is here : https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features
You can see that there is no mention of redirect https in the FrontendConfig part yet.

**Comment by spencerhance** [comment]
Hi @tvvignesh We have still not officially released this in GKE unfortunately.  This is currently available in all Ingress-GCE 1.10 versions.

@iagomelanias that setup looks correct.

**Comment by tibers** [comment]
fix plzzzzzzzz I am doing a deployment call right now and they just asked about this.

**Comment by smarkwell** [comment]
> 
> 
> fix plzzzzzzzz I am doing a deployment call right now and they just asked about this.

As someone who is also still waiting for this solution, the work around I have in place today (without spinning up some insane nginx/haproxy/httpd stack inside my cluster) is to stop listening to http on my k8s cluster.

`kubernetes.io/ingress.allow-http: "false"`

Then you are free to setup an entirely separate load balancer at google, on the same IP address that does nothing but listen on port 80 and return permanent redirect (or your preference) to port 443.  

- https://cloud.google.com/kubernetes-engine/docs/concepts/ingress-xlb#disabling_http
- https://cloud.google.com/load-balancing/docs/https/setting-up-http-https-redirect

**Comment by sdrush-mw** [comment]
Yeah, we have hit upon the same solution - enabling a separate compute engine load balancer on the the same frontend IP port with no backends just firing redirects, but it boggles the mind that a simple feature that has been on the GLB for 6 months STILL is not available in GKE.

**Comment by dinvlad** [comment]
Another solution here is a bucket backend which servers a redirect page.

**Comment by spencerhance** [comment]
> @spencerhance Any relation between GKE version and GCE ingress version? I have been looking at Rapid channel release notes since it is expected to arrive soon. But, not sure which version of GCE ingress is included with it. For instance, this was released 2 days ago and I am not able to see a release note...

Hi @tvvignesh,

Typically we tag releases in open source and soak them internally before we release them in GKE.  We usually update the changelog here https://github.com/kubernetes/ingress-gce#gke-version-mapping when an image is officially released in GKE.  Sometimes the images are released in rapid before we officially launch a feature and update the docs :)

**Comment by pdecat** [comment]
Quick question: why is v1.18.0 still referenced as `latest` while that version is not even in the version mapping list?

https://github.com/kubernetes/ingress-gce/releases/latest redirects to https://github.com/kubernetes/ingress-gce/releases/tag/v1.8.0

**Comment by spencerhance** [comment]
@pdecat That is an error, we have unfortunately not kept our releases and tags in sync: https://github.com/kubernetes/ingress-gce/issues/1216

**Comment by tvvignesh** [comment]
Thanks @spencerhance for the clarification. Will wait (even if its going to be an "unofficial" release 😉)

**Comment by obedtandadjaja** [comment]
@spencerhance Excited about this feature, is there an ETA for it?

**Comment by dldereklee** [comment]
Is there a chance this will work with internal ingress in the future?

**Comment by hadim** [comment]
I have also tested the following config:

```yaml
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: argo-remote-frontend-config
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT  # 301 code
```

but once applied, k8s says the configuration is invalid. If I force the deployment without validation nothing happens on the LoadBalancer.

I am using `GKE 1.17.12-gke.1504`. Not sure at which application-level this feature is deployed since the release notes (https://cloud.google.com/kubernetes-engine/docs/release-notes#november_13_2020) says nothing about GKE/k8s version.

**Comment by anderspetersson** [comment]
@hadim Looks like you need 1.18.10+600 https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features

**Comment by hadim** [comment]
Thanks, @anderspetersson. Somehow I missed it.

**Comment by spencerhance** [comment]
Hey Folks, [this is now available in 1.18.10-gke.600+](https://cloud.google.com/kubernetes-engine/docs/release-notes#november_13_2020)!  Thank you all for your patience.  We also have already planned support in 1.17 and are targeting end of this month.

**Comment by mark-church** [comment]
[This tutorial](https://github.com/GoogleCloudPlatform/gke-networking-recipes/tree/master/ingress/secure-ingress) has an example of managed certs, SSL Policy, and HTTPS redirects together in an Ingress which might be helpful as well!

**Comment by pgp** [comment]
Hi, any news about the possibility of completely disabling plain HTTP (a.k.a. not exposing port 80 at all) from ingress settings?
There had been some discussion in this other [issue](https://github.com/kubernetes/ingress-gce/issues/764) but I don't know if this has been taken into account as possible feature.

**Comment by mehdicopter** [comment]
Yes @pgp you can. Take a look here : https://cloud.google.com/kubernetes-engine/docs/concepts/ingress-xlb#disabling_http

**Comment by pgp** [comment]
I am already using the annotation: `kubernetes.io/ingress.allow-http: "false"` in my configuration, however that doesn't translate in a low-level disable, but only application-level (i.e. gcp responds with a 404, instead of the browser showing a Connection reset message, which is what I would expect if port 80 on the ingress was totally blocked)

**Comment by boredabdel** [comment]
@pgp How does your ingress spec looks like ?

**Comment by pgp** [comment]
here it is (clearly, I've removed runtime annotations added by GKE, and anonymized resource names):
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: my-global-static-ip-resource-name
    networking.gke.io/managed-certificates: my-managed-cert-resource-name
  creationTimestamp: "2020-05-15T00:00:00Z"
  finalizers:
  - networking.gke.io/ingress-finalizer-V2
  generation: 7
  name: my-ingress-resource-name
  namespace: default
spec:
  rules:
  - host: my.public.domain.com
    http:
      paths:
      - backend:
          serviceName: my-first-service
          servicePort: 59999
        path: /first/*
        pathType: ImplementationSpecific
      - backend:
          serviceName: my-second-service
          servicePort: 80
        path: /*
        pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
    - ip: 12.34.56.78

```

**Comment by boredabdel** [comment]
Yeah i have a similar ingress with allow-http set to false and my browser shows 404. That's the expected behavior for GCLB.

**Comment by pgp** [comment]
Indeed, also my ingress sends a 404 as response in that case. My question was about the possibility of totally disabling port 80, instead of sending the request in cleartext using the wrong protocol and then receiving a 404 as response.

**Comment by boredabdel** [comment]
So the 404 is returned from the LoadBalancers, it doesn't reach your application. Your browser send a request to the IP:80, it's gets to the loadBalancing layer which reply as 404 (aka we don't know what is this). You cannot disable 80 completely.

**Comment by pgp** [comment]
So, this is a limitation of the load balancer, and not of the ingress resource...

**Comment by spacejam101** [comment]
Any news in supporting this in 1.17? :)

**Comment by dconvers1979** [comment]
Here is an update: [here](https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#https_redirect)

**Comment by cport1** [comment]
> Here is an update: [here](https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#https_redirect)

FINALLY!

**Comment by mlarcher** [comment]
So... it's still 1.18.10-gke.600 hence not in the "regular channel", or am I missing something ?

**Comment by strigona-worksight** [comment]
> So... it's still 1.18.10-gke.600 hence not in the "regular channel", or am I missing something ?

I have successfully applied the change on a 1.17.13-gke.2600 cluster.

**Comment by abbec** [comment]
> > So... it's still 1.18.10-gke.600 hence not in the "regular channel", or am I missing something ?
> 
> I have successfully applied the change on a 1.17.13-gke.2600 cluster.

Really? I can apply it but not get it to work on 1.17.14-gke.1200.

**Comment by strigona-worksight** [comment]
> > > So... it's still 1.18.10-gke.600 hence not in the "regular channel", or am I missing something ?
> > 
> > 
> > I have successfully applied the change on a 1.17.13-gke.2600 cluster.
> 
> Really? I can apply it but not get it to work on 1.17.14-gke.1200.

Check your events - I had to delete & recreate my ingress for it to apply properly. Additionally, can you confirm that you [associated your FrontendConfig to your ingress](https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#associating_frontendconfig_with_your_ingress)?

**Comment by abbec** [comment]
Ah, missed that, thanks!

**Comment by hari-dmartlabs** [comment]
Ive tried this on 1.17.14-gke.400 and it works. It actually created another LB with a rule to send http traffic to https. Had to set ingress.allow-http: "true" for it to work.

**Comment by billydh** [comment]
does anyone know if we can use terraform for this?

**Comment by goobysnack** [comment]
> does anyone know if we can use terraform for this?

There's no baked in annotation, so you have to create it, then reference it in your annotation in `kubernetes_ingress` - I THINK.  Going to try this myself here shortly.  I don't know if that changes / removes all the other default front end config that k8s creates.  I'll report back.  

```
resource "null_resource" "fe-config" {
  provisioner "local-exec" {
    command = <<EOT
kubectl create -f - -- <<EOF
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: frontend-config
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
EOF
EOT
  }
}

resource "kubernetes_ingress" "ingress" {
  wait_for_load_balancer = true
  metadata {
    name = ingress-name
    namespace = namespace
    annotations = {
      "networking.gke.io/FrontendConfig" = "frontend-config"
      ...other annotations removed...

**Comment by spencerhance** [comment]
For those very patient users on 1.16, this is now supported in 1.16.15-gke.11200+ 😃

**Comment by billysegarloka** [comment]
@spencerhance link or reference or example please?

**Comment by boredabdel** [comment]
@billysegarloka you can find an example here https://github.com/GoogleCloudPlatform/gke-networking-recipes/blob/master/ingress/secure-ingress/secure-ingress.yaml

The explanation is here https://github.com/GoogleCloudPlatform/gke-networking-recipes/tree/master/ingress/secure-ingress

**Comment by goobysnack** [comment]
should be plural as it turns out.

    annotations = {
      "networking.gke.io/crontendconfigs" = "frontend-config"
      ...other annotations removed...

Based on `kubectl api-resources`

`frontendconfigs                                networking.gke.io              true         FrontendConfig`

**Comment by unitof** [comment]
@goobysnack Just a heads up it's `frontendconfigs`, not `crontend`. But that does sound like a decent cron manager tool!

**Comment by goobysnack** [comment]
> @goobysnack Li’l typo: it's `frontendconfigs`, not `crontend`. But that does sound like a decent cron manager tool!

OOPSIE!

**Comment by goobysnack** [comment]
FYI this didn't work:

```
kubectl get frontendconfigs frontend-config -o yaml
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  creationTimestamp: "2021-03-23T14:08:33Z"
  generation: 1
  managedFields:
  - apiVersion: networking.gke.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:redirectToHttps:
          .: {}
          f:enabled: {}
          f:responseCodeName: {}
    manager: kubectl
    operation: Update
    time: "2021-03-23T14:08:33Z"
  name: frontend-config
  namespace: default
  resourceVersion: "6306812"
  selfLink: /apis/networking.gke.io/v1beta1/namespaces/default/frontendconfigs/frontend-config
  uid: 8726971f-f1b6-43df-8624-0552ad0168a2
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
```

the annotation is set in the ingress:

```
kubectl get ingress ingress-helloworld-test-foo-io -o yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.gcp.kubernetes.io/pre-shared-cert: cert-helloworld-test-foo-io
    ingress.kubernetes.io/backends: '{"k8s1-44e1677e-default-hellonode-80-4d54c10a":"HEALTHY"}'
    ingress.kubernetes.io/forwarding-rule: k8s2-fr-ov9ubdnk-default-ingress-helloworld-test-foo-474zxxxd
    ingress.kubernetes.io/https-forwarding-rule: k8s2-fs-ov9ubdnk-default-ingress-helloworld-test-foo-474zxxxd
    ingress.kubernetes.io/https-target-proxy: k8s2-ts-ov9ubdnk-default-ingress-helloworld-test-foo-474zxxxd
    ingress.kubernetes.io/ssl-cert: cert-helloworld-test-foo-io
    ingress.kubernetes.io/target-proxy: k8s2-tp-ov9ubdnk-default-ingress-helloworld-test-foo-474zxxxd
    ingress.kubernetes.io/url-map: k8s2-um-ov9ubdnk-default-ingress-helloworld-test-foo-474zxxxd
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: vip-helloworld-test-foo-io
    networking.gke.io/frontendconfigs: frontend-config
```
But, it's not working:
```
curl -vvv -L http://helloworld-test.foo.io
* Rebuilt URL to: http://helloworld-test.foo.io/
*   Trying <removed>...
* Connected to helloworld-test.foo.io (<removed>) port 80 (#0)
> GET / HTTP/1.1
> Host: helloworld-test.foo.io
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Tue, 23 Mar 2021 16:16:33 GMT
< Transfer-Encoding: chunked
< Via: 1.1 google
< 
Hello World!

{
    "host": "helloworld-test.foo.io",
    "user-agent": "curl/7.47.0",
    "accept": "*/*",
    "x-cloud-trace-context": "e1a08869018f1e349afaff0d8b778b4a/2170462711055636813",
    "via": "1.1 google",
    "x-forwarded-for": "<removed>",
    "x-forwarded-proto": "http",
    "connection": "Keep-Alive"
* Connection #0 to host helloworld-test.foo.io left intact
```

**Comment by boredabdel** [comment]
In the Ingress object, replace this annotation 
```
  networking.gke.io/frontendconfigs: frontend-config
```

With this one
```
networking.gke.io/v1beta1.FrontendConfig:  frontend-config
```

**Comment by rk185151** [comment]
Thank you @boredabdel

**Comment by billysegarloka** [comment]
> > does anyone know if we can use terraform for this?
> 
> There's no baked in annotation, so you have to create it, then reference it in your annotation in `kubernetes_ingress` - I THINK. Going to try this myself here shortly. I don't know if that changes / removes all the other default front end config that k8s creates. I'll report back.
> 
> ```
> resource "null_resource" "fe-config" {
>   provisioner "local-exec" {
>     command = <<EOT
> kubectl create -f - -- <<EOF
> apiVersion: networking.gke.io/v1beta1
> kind: FrontendConfig
> metadata:
>   name: frontend-config
> spec:
>   redirectToHttps:
>     enabled: true
>     responseCodeName: MOVED_PERMANENTLY_DEFAULT
> EOF
> EOT
>   }
> }
> 
> resource "kubernetes_ingress" "ingress" {
>   wait_for_load_balancer = true
>   metadata {
>     name = ingress-name
>     namespace = namespace
>     annotations = {
>       "networking.gke.io/FrontendConfig" = "frontend-config"
>       ...other annotations removed...
> ```

@goobysnack did this work?

**Comment by goobysnack** [comment]
> > > does anyone know if we can use terraform for this?
> > 
> > 
> > There's no baked in annotation, so you have to create it, then reference it in your annotation in `kubernetes_ingress` - I THINK. Going to try this myself here shortly. I don't know if that changes / removes all the other default front end config that k8s creates. I'll report back.
> > ```
> > resource "null_resource" "fe-config" {
> >   provisioner "local-exec" {
> >     command = <<EOT
> > kubectl create -f - -- <<EOF
> > apiVersion: networking.gke.io/v1beta1
> > kind: FrontendConfig
> > metadata:
> >   name: frontend-config
> > spec:
> >   redirectToHttps:
> >     enabled: true
> >     responseCodeName: MOVED_PERMANENTLY_DEFAULT
> > EOF
> > EOT
> >   }
> > }
> > 
> > resource "kubernetes_ingress" "ingress" {
> >   wait_for_load_balancer = true
> >   metadata {
> >     name = ingress-name
> >     namespace = namespace
> >     annotations = {
> >       "networking.gke.io/FrontendConfig" = "frontend-config"
> >       ...other annotations removed...
> > ```
> 
> @goobysnack did this work?

It did after I made the suggested change by @boredabdel

I'm repeating a similar exercise now for access logging.  I mean, this is duct tape and bailing wire stuff from Google.

**Comment by boredabdel** [comment]
Folks, i would appreciate if you have a look at https://github.com/GoogleCloudPlatform/gke-networking-recipes.

We are trying to document all potential ways of using Ingress with most of the important features, in an educational way. So far focusing on providing explanation and YAML files.

If you could have a look, try them out and log an issue if you see something missing or should be fixed i would appreciate it

Thank you

**Comment by badrange** [comment]
Is there something left to do in this issue or can it be considered fixed and thus closed?

**Comment by goobysnack** [comment]
> Is there something left to do in this issue or can it be considered fixed and thus closed?

I have other issues, but not redirect!  Honestly, it should be available without having to configure a custom backend.

**Comment by mark-church** [comment]
@goobysnack you're saying that HTTPS redirects should be on by default if HTTPS/443 is on? That's an interesting idea. It would certainly be difficult to transition all the existing Ingress users to that right now though. Anybody who has an Ingress with 80/443 open and is expecting traffic on port 80 to work would find that it doesn't receive traffic anymore if we made HTTPS redirects default. On the other hand I would expect that it's a rare (if not non-existent) use-case to have 80 & 443 open but intentionally receive traffic on port 80 that is sent to a non-HTTPS service. Does anybody have this kind of requirement in which a default HTTP redirect would break their setup?

**Comment by Cyral** [comment]
Closing since this is now implemented. See the GCP docs for an example: https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#https_redirect

**Comment by goobysnack** [comment]
> @goobysnack you're saying that HTTPS redirects should be on by default if HTTPS/443 is on? That's an interesting idea. It would certainly be difficult to transition all the existing Ingress users to that right now though. Anybody who has an Ingress with 80/443 open and is expecting traffic on port 80 to work would find that it doesn't receive traffic anymore if we made HTTPS redirects default. On the other hand I would expect that it's a rare (if not non-existent) use-case to have 80 & 443 open but intentionally receive traffic on port 80 that is sent to a non-HTTPS service. Does anybody have this kind of requirement in which a default HTTPS redirect would break their setup?

I'm saying they should be available by default, as a configuration variable/flag/bool without having to configure a frontend.  Same with the backend config for logging.  These should just be simple options, not out of band configs.

**Comment by boredabdel** [comment]
@goobysnack Thanks for the feedback. I agree that the UX is not great on this!
One thing to keep in mind is that it's very hard for us to asses what should be the default behavior because different customers want different things.
From experience customers in the financial service area want HTTP to be completely disabled and don't want any redirect for instance


From what i can see i could enumerate the following use cases
- Ingress is used to expose a webpage, where users could open a webpage on HTTP and get redirected to https. This is what the FrontendConfig CRD give you
- Ingress is used for an API which should be always only accessible on HTTPS. This is what the allow-http annotation gives you.
- Ingress is used to host a website or API which is accessible on both HTTP(rare) and HTTPS.

Hope this helps, we are looking at ways to document this and making it easy to understand

**Comment by Cyral** [comment]
I finally got around to implementing this but am getting a strange error:

```"Error syncing to GCP: error running load balancer syncing routine: loadbalancer default-client-ingress--8d745d5baddfbea0 does not exist: ensureRedirectUrlMap() = error: cannot enable HTTPS Redirects with the V1 Ingress naming scheme.  Please recreate your ingress to use the newest naming scheme."```

Seems like maybe the load balancers need to be re-created so that they use this "V2" naming scheme described [here](https://github.com/kubernetes/ingress-gce/pull/892)? I am not sure really but digging through [the code](https://github.com/kubernetes/ingress-gce/blob/b3a66b567a25d2de65ed6bf62e0cd8e21c0c007e/pkg/loadbalancers/url_maps.go#L104) it seems like it needs a V2 namer, whatever that is. @spencerhance

**Comment by spencerhance** [comment]
@Cyral 

> it sounds like I need to re-create the ingress (that is, the GCP load balancer) to do it

Yes that is unfortunately correct, You need to delete and re-create your ingress.  However, we could probably make that error message less confusing - The naming scheme is a concept internal to the controller, and they are not always backwards compatible.

**Comment by Cyral** [comment]
@spencerhance Thanks for the clarification. What is the best approach for re-creating them without downtime? My thinking is they need to be re-created with new IPs, and then we will switch our DNS to point to the new load balancer IPs, and then manually delete the old load balancers. However I don't know how to trigger k8s to create new load balancers, and also how to make sure it leaves the old ones alone so that we can run both in parallel until the DNS propagates.

**Comment by spencerhance** [comment]
@Cyral 

Ingress lifecycle is tied to the LB lifecycle.  Can you create a new ingress that points to the same service as the current ingress?  This will create a new LB and then you can switch over DNS.  Once that's complete you can delete the original ingress and the old LB will be torn down.

**Comment by Cyral** [comment]
@spencerhance That makes sense, I can do that. Although I will have to call it <ingress-name>2 I suppose.

**Comment by boredabdel** [comment]
@Cyral Yes your new Ingress will have to have a different name than the existing one, Kubernetes will not allow you to create two objects of the same Kind in the same namespace with identical names.

An other Option is to run two clusters with Multi Cluster Ingress, have a single VIP attached to the DNS record your customers use and failover the clusters to do maintenance on your clusters. You can find few examples on how to do that here [1]

[1]https://github.com/GoogleCloudPlatform/gke-networking-recipes/tree/master/multi-cluster-ingress

**Comment by spencerhance** [comment]
@boredabdel 

MultiClusterIngress is great!  However one of the drawbacks is that it doesn't support HTTPS Redirects yet.  This is changing very soon though :)

**Comment by boredabdel** [comment]
Yes correct. We are working on it :) @mark-church FYI

**Comment by red8888** [comment]
Is this supported for private ingresses? I get this error: does not exist: ensureRedirectUrlMap() = error: cannot enable HTTPS Redirects with L7 ILB

**Comment by boredabdel** [comment]
@red8888 The frontendConfig CRD is not supported with Internal HTTP(s) LB. Have a look at this page [1] which contains the compatibility matrix between features and the various types of loadBalancers

[1]https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features

**Comment by gaurav517** [comment]
> @boredabdel
> 
> MultiClusterIngress is great! However one of the drawbacks is that it doesn't support HTTPS Redirects yet. This is changing very soon though :)

Eagerly waiting for this feature. Is there any suggested approach documented somewhere for multi-cluster ingress? Thanks.

**Comment by boredabdel** [comment]
@gaurav517 you can do the http->https redirect in your app. Or maybe run a simple proxy which will redirect http calls to the LB and proxy https directly to your app. I have never done this before so to be tested

**Comment by boredabdel** [comment]
@Gageperrin can you please log an issue against our repo ? https://github.com/GoogleCloudPlatform/gke-networking-recipes

Sorry for asking to duplicate the work but i rather keep our examples bugs in our own repo, just tag me and i will have a look right away

Thanks

**Comment by boredabdel** [comment]
Please also share all your YAML files (MCI, MCS, Deployment, FrontendConfig, and BackendConfig if you have one). Screenshots could help too.

**Comment by collectedview** [comment]
Following these two steps, worked for me, there are articles all over that have the leadup steps, the documentation here should be the latest.

https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features

1. [Associating the Ingress & Frontend Configuration](https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#configuring_ingress_features)

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    networking.gke.io/v1beta1.FrontendConfig: "FRONTENDCONFIG_NAME"
```

2. [Frontend Configuration](https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#https_redirect)

```
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: FRONTENDCONFIG_NAME
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: RESPONSE_CODE
```
