### ISSUE TITLE
rewrite

### ISSUE THREAD

**Issue by AdrienLemaire** [kubernetes/ingress-gce#109]
Hi, I've been struggling to set a rewrite rule for my ingress (GCP Kubernetes with a Deployment, Service NodePort and Ingress). What I'm trying to get is:
* api.example.com/  →  backend/api/
* www.example.com/ → backend/www/

So that my server can server requests whether they start with /api/ or /www/, without a care about the subdomains.

I'm creating this issue because I have a question regarding your comment in https://github.com/kubernetes/ingress-gce#paths
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginxtest-ingress
spec:
  rules:
  - http:
      paths:
      - path: /hostname
        backend:
          serviceName: nginxtest
          servicePort: 80
```

```
Note what just happened, the endpoint exposes /hostname, and the loadbalancer forwarded the entire matching url to the endpoint. This means if you had '/foo' in the Ingress and tried accessing /hostname, your endpoint would've received /foo/hostname and not known how to route it.
```
I wish that was true... for me, loadbalancerip/foo would be the only queryable url, while everything else returns 404 Not Found errors. The Ingress only forward a request if it matches the path, that's it.

Anyways, if you have a suggestion regarding my problem, I'd really appreciate. Couldn't figure out how to get it working with annotations [rewrite-url or app-root](https://github.com/kubernetes/ingress-nginx/blob/master/docs/examples/rewrite/README.md)

**Comment by AndyBarron** [comment]
https://github.com/kubernetes/ingress-gce/blob/master/docs/annotations.md#url-related

Unfortunately, it seems that `rewrite-target` is not supported by the GCE ingress. This has been a pain point for me, too :/

**Comment by thecodejunkie** [comment]
No updates on this?

**Comment by nicksardo** [comment]
This is an upstream request to GCP load balancing: https://cloud.google.com/support/docs/issue-trackers
/close

**Comment by AndyBarron** [comment]
Are there any updates on this? I cannot find anything related to it in the issue tracker.

**Comment by bowei** [comment]
We most likely can't support this until the GCLB supports this. I would recommend looking at the open public issues and voting for rewriting for L7 load balancing:

https://issuetracker.google.com/savedsearches/559790

**Comment by AndyBarron** [comment]
Thank you for the quick response! Shame it's blocked though. Maybe time to wrestle with the Nginx ingress then.

**Comment by mkozjak** [comment]
Are there any updates for this feature? It's a basic ingress' feature and we'd like to have one.

**Comment by bukzor** [comment]
The alpha API shows an alternative to "service" in "routeAction" which has a "urlRewrite" attribute.

https://developers.google.com/resources/api-libraries/documentation/compute/alpha/python/latest/compute_alpha.urlMaps.html#insert

```
        "urlRewrite": { # The spec for modifying the path before sending the request to the matched backend service. # The spec to modify the URL of the request, prior to forwarding the request to the matched service
          "hostRewrite": "A String", # Prior to forwarding the request to the selected service, the request's host header is replaced with contents of hostRewrite.
              # The value must be between 1 and 255 characters.
          "pathPrefixRewrite": "A String", # Prior to forwarding the request to the selected backend service, the matching portion of the request's path is replaced by pathPrefixRewrite.
              # The value must be between 1 and 1024 characters.
        },
```

So I guess it's coming? Someday?

**Comment by jgirdner** [comment]
Talk about limitations........

**Comment by diversario** [comment]
Wow, spent 4 hours banging my head on the desk and this is why 🤣

**Comment by thesayyn** [comment]
I can't believe that this is not supported.

**Comment by ramonvermeulen** [comment]
This should really be supported in GKE..

**Comment by drewsymo** [comment]
+1 Would love to see this supported

**Comment by sly01** [comment]
+1 I would like to see as well.

**Comment by ignacio83** [comment]
+1

**Comment by frank12001** [comment]
+1

**Comment by aeneasr** [comment]
This is such a basic feature, it literally makes ingress with path matching unusable in almost 99% of the use cases. It is so frustrating to see such basic issues being open for 1 1/2 years and apparently no one from Google side gives a single ... The experience with Google Cloud is as always (and so frustrating and annoying, it's like Microsoft under Ballmer): Yeah talk to this team. Oh we can't do anything, please talk to this team. Ah yeah please create an issue in this tracker. Oh yeah well we still don't care enough to fix it. Infuriating.

By the way, the [annotation docs](https://github.com/kubernetes/ingress-gce/blob/master/docs/annotations.md#url-related) have disappeared too and maybe I'm blind but I tried to find a list of supported annotations by this Ingress for over an hour without luck.

ps: Thanks for letting me vent.

**Comment by ramonvermeulen** [comment]
Eventually ended up putting a nginx back-end in front of the back-end services I did need to target to do the HTTP -> HTTPS redirect, not ideal tho. I really hope Google will get this feature in place.

**Comment by loxy** [comment]
WTF. Ridiculous...

**Comment by thockin** [comment]
Hey folks, let's keep it professional, please.

I don't disagree that this seems like a great feature, but the simple fact is that it isn't available yet.

**Comment by charlie-lk** [comment]
I think the real fact is that it is a great and one of the most essential features which Google have opened tickets as long as one and half years for.

But - yes. Let's be professional. Don't be like GKE ingress.

**Comment by mariusz-jasinski** [comment]
Amazing Google, no simple features inside Ingress:
- no rewrite
- no redirect http to https
:-(

**Comment by dazzbourgh** [comment]
Bruh, spent 2 days trying to figure out what I'm doing wrong, but it's 2020 and they still don't support it?

**Comment by RoysyLee** [comment]
I'm frustrated..... this issue suggested in 2018..and now is 2020!!

**Comment by rohansingh** [comment]
I believe this is supported by the GCE load balancer now. For example, here is a load balancer that was created via an ingress. In the console, I could manually switch to use *Advanced host and path rule*, which allows me to specify a URL rewrite:

<img width="1148" alt="HTTP(S) load balancer console" src="https://user-images.githubusercontent.com/615175/79015279-75a09800-7b3a-11ea-9413-d3ff8036a52d.png">

@bowei @skmatti Am I misunderstanding what I'm seeing above? If this is possible to do now, perhaps this issue can be unfrozen?

**Comment by thesayyn** [comment]
@rohansingh, As far as I know, that configuration applies to the whole load balancer and ingresses are tied to a single load balancer.  So what happens when I create separate ingresses in the cluster?

**Comment by rohansingh** [comment]
@thesayyn It's no different than how paths work now without rewrites. Just instead of "Advanced host and path rule", ingress-gce currently uses the "Simple host and path rule" which doesn't support rewrites.

Additionally, no, pretty sure each ingress creates its own load balancer.  For example, my load balancer above is named after the ingress that created it.

**Comment by thesayyn** [comment]
If that's the case, we could send a PR. 
I'll take a look at it first thing tomorrow.

**Comment by StephenWithPH** [comment]
confirming that this is GA now: https://issuetracker.google.com/issues/35904733#comment95

**Comment by rohansingh** [comment]
Yeah, so this should be totally possible now. Unfortunately I don't have time to dig into the implementation right now, and I have a workaround that works. But for folks up-thread who seem to think this is a major dealbreaker, maybe someone has time to look into it?

**Comment by oshamin** [comment]
Is it possible to configure the rewrite rules via Ingress manifest?
Or you need to use gcloud CLI /Google Console for that?

**Comment by eduartua** [comment]
> Is it possible to configure the rewrite rules via Ingress manifest?
> Or you need to use gcloud CLI /Google Console for that?

Didn't work for me via Ingress manifest.

**Comment by mat-613** [comment]
@bowei any news for the implementation via ingress manifests?

**Comment by charlie-lk** [comment]
While we are waiting for this, Nginx ingress has gone a long way.  I recently used it to set up a new project and it worked great. It was a bit difficult at the beginning to set up. But once configured properly, it works great.

Start with Kubernetes Nginx Ingress https://kubernetes.github.io/ingress-nginx/

(There is an Nginx version of this too. But above was what I worked with)

Use Helm to install it and configure rewrites with pattern matching

https://kubernetes.github.io/ingress-nginx/deploy/

https://stackoverflow.com/questions/61185530/another-nginx-ingress-rewrite-target-problem

**Comment by tudorgrig** [comment]
Can somebody please reply if the problem stated by me has the same issue as described here? https://stackoverflow.com/questions/63979711/404-not-found-response-on-every-https-ingress-request?noredirect=1#comment113135797_63979711

**Comment by lgelfan** [comment]
> Can somebody please reply if the problem stated by me has the same issue as described here? https://stackoverflow.com/questions/63979711/404-not-found-response-on-every-https-ingress-request?noredirect=1#comment113135797_63979711

If what you're saying is that you are expecting a rewrite, then yes.

**Comment by jhordies** [comment]
Still same issue here, please keep this alive  /remove-lifecycle rotten

**Comment by spacejam101** [comment]
Wow Spent 2 days for this issue and turns out its not currently supported :(  This is the only thing that is holding us from using Cloud iap, client ip preservation, cloud armor and many more :(

**Comment by cslovell** [comment]
This is ridiculous.

**Comment by ajaymaity** [comment]
This feature is still not supported? It's 2021!

**Comment by bowei** [comment]
/reopen

You should also check out https://cloud.google.com/kubernetes-engine/docs/concepts/gateway-api#gatewayclass, as you may find the feature exists there.

**Comment by JamesXNelson** [comment]
I went and voted on the issue tracker items linked here, hopefully it helps them get picked up someday.

**Comment by Gaen** [comment]
srsly?

/reopen
/remove-lifecycle rotten

**Comment by adrian-gierakowski** [comment]
this issue should be reopened

**Comment by AlisonOSouza** [comment]
+1 
Please reopen this issue!

**Comment by bygui86** [comment]
after 3 years of discussion I think this feature won't be done

**Comment by davidb-e4s** [comment]
+1

**Comment by sahilrajput03** [comment]
Even nginx-ingress doesn't seem to work according to me..

I found two issues facing path rewrite issue @

1. https://github.com/kubernetes/ingress-nginx/issues/8316
2. https://github.com/kubernetes/ingress-nginx/issues/8317

**Comment by MishaVeldhoen** [comment]
Would be really convenient to have this!

**Comment by 0sax** [comment]
+1

**Comment by MaroonedMind** [comment]
It's been more than 4 years and there's still no progress on this. 
I find this kind of reaction, or rather lack thereof, to be very strange considering it's an essential feature request. 
What a deal-breaker.

**Comment by pkerschbaum** [comment]
Hey @masus04!

At a project I am working on, we migrated from one domain to a new domain. We wanted to redirect all users using the old domain to the new domain.

We successfully deployed a workaround for this scenario which goes like this: the GCP Ingress does not allow rewrites/redirects; however, it allows to "route requests to different backend services depending on the URL path" (see https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#multiple_backend_services).  
So we deployed an Nginx service+deployment which only purpose is to redirect all incoming requests. We defined that Nginx as "default backend", and only the new domain as additional backend.

See the following k8s resource definitions.  
"my-domain.com" would be the domain the users should be redirected to.  
Please note that I had to manually configure a health check for the nginx Service because otherwise, the health check would have got 301 responses from the nginx Deployment, and those are considered "unhealthy".

### Ingress:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
spec:
  defaultBackend:
    service:
      name: nginx-redirect-service
      port:
        number: 80
  rules:
    - host: my-domain.com
      http:
        paths:
          - backend:
              service:
                name: my-domain-service
                port:
                  number: 80
            pathType: ImplementationSpecific
```

### nginx Service:

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/backend-config: '{ "ports": { "80": "nginx-redirect-service-backendconfig" } }'
    cloud.google.com/neg: '{ "ingress": true }'
  name: nginx-redirect-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx-redirect-deployment
  type: ClusterIP

```

### nginx BackendConfig (to configure health check):

```yaml
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: nginx-redirect-service-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 80
    requestPath: /nginx-redirect-health
    type: HTTP
```

### nginx configuration (as ConfigMap):

```yaml
apiVersion: v1
data:
  nginx.conf: |
    user nginx;
    worker_processes 1;
    events {
      worker_connections 10240;
    }
    http {
      server {
        listen 80 default_server;
        listen [::]:80 default_server;

        location / {
          return 301 https://my-domain.com$request_uri;
        }

        location = /nginx-redirect-health {
          return 200 'health OK';
          add_header Content-Type text/plain;
        }
      }
    }
kind: ConfigMap
metadata:
  name: nginx-redirect-configmap
```

### nginx Deployment:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-redirect-deployment
  name: nginx-redirect-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-redirect-deployment
  template:
    metadata:
      labels:
        app: nginx-redirect-deployment
    spec:
      containers:
        - image: nginx
          name: nginx-redirect-deployment
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-conf
              readOnly: true
              subPath: nginx.conf
      volumes:
        - configMap:
            items:
              - key: nginx.conf
                path: nginx.conf
            name: nginx-redirect-configmap
          name: nginx-conf

```

**Comment by masus04** [comment]
Thx @pkerschbaum I'll consider it :+1:

**Comment by swetharepakula** [comment]
The Gateway API natively allows specifying rewrites. We will look into supporting this through the Gateway API.

**Comment by masus04** [comment]
> The Gateway API natively allows specifying rewrites. We will look into supporting this through the Gateway API.

What API is this exactly and is there an issue we can follow the progress on?

**Comment by softwareplumber** [comment]
*shakes head* it took four years to not implement this basic feature and we're expected to believe that the yet-more-complicated Gateway API will be fit for use?

**Comment by masus04** [comment]
Having switched from Ingress to Gateway primarily because of this issue I think the Gateway API is definitely an improvement and the separation of HttpRoutes simplify the setup.

However, while the URL rewrite is part of the API specification, it appears the GCP implementation of it does not yet support the rewrite functionality.

**Comment by jaroslawhartman** [comment]
It's a shame that such basic functionality is not supported. Please reopen‼️

**Comment by grzegorzjudas** [comment]
There is (seemingly) related item in Google's issue tracker that I think they use to prioritize stuff: https://issuetracker.google.com/issues/194125076. Please vote on it, may help getting this finally implemented.

**Comment by dryleaf** [comment]
Since 2018, this issue is still not fixed. Unbelievable!!!
<img class="emoji" alt="thinking_face" src="https://github.githubassets.com/images/icons/emoji/unicode/1f615.png" width="20" height="20">

**Comment by cyberhorsey** [comment]
Lol

**Comment by davidivkovic** [comment]
This is a joke!

**Comment by grzegorzjudas** [comment]
May help some of you, as I struggle(d) with this for a long time, too: I don't think Kubernetes/Google team is ever going to implement it, given it's been so long - at I agree this **is a joke**. But!

While it's not necessarily in a state (yet) that some consider production-ready, there already is a successor for the Ingress resource based routing, that is Gateway API:
- https://gateway-api.sigs.k8s.io/
- https://cloud.google.com/kubernetes-engine/docs/concepts/gateway-api

Given how Ingress implementations deviate based on providers and what amazing things Gateways can achieve, I have tried using Gateway-based approach in GKE and, probably because supporting rewrite is kind of necessary to implement it at all, it works. Have it a go!

**Comment by jgirdner** [comment]
Sitting here sipping coffee reading these comments after 5 years of getting notifications from this thread 😂

**Comment by grzegorzjudas** [comment]
Rather sad news, but it looks like as of now, rewrites are not supported even as part of Gateway API (https://gateway-api.sigs.k8s.io/guides/http-redirect-rewrite/#rewrites). Following:
```yaml
- filters:
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /
```
results in:
```
error: error validating "httproute.yaml": error validating data: ValidationError(HTTPRoute.spec.rules[1].filters[0]): unknown field "urlRewrite" in io.k8s.networking.gateway.v1beta1.HTTPRoute.spec.rules.filters; if you choose to ignore these errors, turn validation off with --validate=false
```
Available filters are basically ones listed [here](https://cloud.google.com/kubernetes-engine/docs/how-to/gatewayclass-capabilities#httproute).
