### ISSUE TITLE
MultiClusterIngress with CDN

### ISSUE THREAD

**Issue by LeifRoss** [kubernetes/ingress-gce#1093]
Hi, I am experiencing a slight issue that has turned out to be quite the showstopper.  I have set up a multi cluster ingress, and I am attempting to set up CDN for the static files. I followed this guide which works fine for regular ingresses, but nothing happens when using the MultiClusterIngress, and setting up the CDN manually from the load balancer works for a while, but it gets deleted randomly between 2 and 5 minutes after creation(?).

Is there something special that needs to be setup for Cloud CDN to be working for the MultiClusterIngress Load Balancer, or is there another approach that is suitable for serving a few static files to a huge amount of clients? (a SPA)

The guide: https://cloud.google.com/kubernetes-engine/docs/how-to/cdn-backendconfig

```
apiVersion: networking.gke.io/v1
kind: MultiClusterIngress
metadata:
  name: zone-ingress-facade
  namespace: prod
  annotations:
    kubernetes.io/ingress.global-static-ip-name: facade-mci-address-mk1
    networking.gke.io/managed-certificates: facade-cert-mci
spec:
  template:
    spec:
      backend:
        serviceName: zone-facade
        servicePort: 80

-------------------------------------------

apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata:
  name: zone-facade
  namespace: prod
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"cdn-config"}}' // have attempted using the name http outright here
spec:
  template:
    spec:
      type: NodePort
      selector:
        app.kubernetes.io/instance: facade
        app.kubernetes.io/name: facade
      ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: http

-------------------------------------------

  apiVersion: cloud.google.com/v1beta1
  kind: BackendConfig
  metadata:
    namespace: prod
    name: cdn-config
  spec:
    cdn:
      enabled: true
      cachePolicy:
        includeHost: true
        includeProtocol: true
        includeQueryString: false

```
