### ISSUE TITLE
Ingress without default backend explicitly configured doesn't work at all

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/ingress-gce#110]
I'm trying to create a fanout ingress on GKE (v1.7):

- `/*` &rarr; `cats` Service
- `/dogs/*` &rarr; `dogs` Service

When I deploy these resources, after LB is configured fine (I can hit the gke `default backend: 404`), I can neither get `http://IP/` or `http://IP/dogs/` to work. I always get either `default backend: 404` or HTTP 502 from Google’s LB.

Is it because I don't have a `spec.backend` that returns 200 OK on `GET /`? From the documentation, I expect this to work.

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cats-and-dogs
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: cats
          servicePort: 8080
      - path: /dogs/*
        backend:
          serviceName: dogs
          servicePort: 8080
```

```yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cats
  labels:
    app: cats
spec:
  template:
    metadata:
      labels:
        app: cats
    spec:
      containers:
      - name: web
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: cats
  name: cats
spec:
  type: NodePort
  selector:
    run: cats
  ports:
  - port: 8080
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dogs
  labels:
    app: dogs
spec:
  template:
    metadata:
      labels:
        app: dogs
    spec:
      containers:
      - name: web
        image: gcr.io/google-samples/hello-app:2.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: dogs
  name: dogs
spec:
  type: NodePort
  selector:
    run: dogs
  ports:
  - port: 8080
```

/cc @nicksardo
