### ISSUE TITLE
Ingress Update Issue/s (Changing Backend/Rules)

### ISSUE THREAD

**Issue by kpurdon** [kubernetes/ingress-gce#1117]
Sorry for the generic title. I'm having issues updating/changing an ingress. My goal here was to add host validation and switch to the default 404 backend.

Starting with an ingress like:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myingress
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: "myglobalip"
    ingress.gcp.kubernetes.io/pre-shared-cert: "mysharedcert"
spec:
  backend:
    serviceName: myservice
    servicePort: 80
```

I changed the ingress spec to:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myingress
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: "myglobalip"
    ingress.gcp.kubernetes.io/pre-shared-cert: "mysharedcert"
spec:
  rules:
    - host: "*.mydomain.io"
      http:
        paths:
          - path: /*
            backend:
              serviceName: myservice
              servicePort: 80
```

My hope was that this would result in an ingress/lb w/ the default 404 backend, and a single rule allowing only requests w/ the valid host `*.mydomain.io` through to the defined backend. What happened was that I ended up w/ a third new rule (the host rule) and the previous backends still in place.

Additionally I tried completely deleting the ingress/lb/rules/etc (I've seen all the issues about things not getting deleted and did as best I could to fully delete everything w/ the `gcloud` command).  When applying the new ingress after this deletion I ended up in the same state as if I had just applied the change (which is quite odd).

My question is: should a change like this be possible, and if so, how should it be done?
