### ISSUE TITLE
Error during sync: error running backend syncing routine: unable to find nodeport in any service

### ISSUE THREAD

**Issue by warent** [kubernetes/ingress-gce#1146]
Hi, I hope you're doing well. Bashing my head against an ingress issue and beginning to wonder if this is a bug.

I've defined my service and deployment like so:
```
apiVersion: v1
kind: Service
metadata:
  name: sherpa
spec:
  selector:
    app: sherpa-deployment
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sherpa-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sherpa-deployment
  template:
    metadata:
      labels:
        app: sherpa-deployment
    spec:
      containers:
        - name: sherpa-deployment
          image: gcr.io/montfont/sherpa:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
```

Seems to work:

```
➜  k8s kubectl get service
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)        AGE
kubernetes   ClusterIP   10.8.0.1     <none>        443/TCP        37h
sherpa       NodePort    10.8.15.78   <none>        80:30995/TCP   4m17s
```

I don't know if I should be concerned about the 80:30995 mapping it shows or if that's expected.

```
➜  k8s kubectl get po
NAME                                READY   STATUS    RESTARTS   AGE
sherpa-deployment-fcb99c996-vtf7z   1/1     Running   0          8m24s
```

Then I define an ingress:

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sherpa-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "api-ip-1"
spec:
  backend:
    serviceName: sherpa
    servicePort: 80
```

It doesn't deploy for some reason.
![Screen Shot 2020-06-09 at 12 48 36 PM](https://user-images.githubusercontent.com/13342266/84193035-b2f8a780-aa4f-11ea-856f-c68bc82cb1e4.png)

![Screen Shot 2020-06-09 at 12 53 20 PM](https://user-images.githubusercontent.com/13342266/84193388-39ad8480-aa50-11ea-8878-b8725b5d04d4.png)

I've reviewed my yaml several times and compared against docs but don't see what is wrong. Is this a bug?
