### ISSUE TITLE
Support for services of type "ExternalName"

### ISSUE THREAD

**Issue by migueloller** [kubernetes/ingress-gce#1169]
When adding an ingress to expose a service of "ExternalName", the following error message appears:

```
error while evaluating the ingress spec: service "cdn-how-to/my-service" is type "ExternalName", expected "NodePort" or "LoadBalancer"
```

Does the controller only support services of type "NodePort" and "LoadBalancer"? The NGINX ingress controller doesn't have this issue.

**Comment by rramkumar1** [comment]
@migueloller What is the use case?

**Comment by migueloller** [comment]
GCP Cloud Functions don't have support for Cloud CDN. If one could use a service of type `ExternalName`, one could then use GCP CDN via an ingress resource and have the cluster proxy those requests to the Cloud Functions host.

Another use case is hosting something like Intercom help pages on your own domain that point to the Kubernetes cluster. For example, we have a DNS A record for `*.example.com` that points to our cluster. We can then use in ingress resource to redirect `help.example.com` traffic to the desired host. The reason this is convenient if because SSL cert creation can be handled by Kubernetes as well. Simply adding a DNS record won't do. We currently achieve this using the NGINX ingress controller and cert-manager. This is only possible because the NGINX ingress controller supports services of type `ExternalName`.

More generically, what one would have to set up via HTTP(s) load balancers and internet NEGs in GCP, one could just do via Kubernetes with support for services of type `ExternalName`.

**Comment by rramkumar1** [comment]
@prameshj Any thoughts here since this is sort of related to DNS? I'm not too familiar with ExternalName services

**Comment by prameshj** [comment]
> 
> More generically, what one would have to set up via HTTP(S) load balancers and internet NEGs in GCP, one could just do via Kubernetes with support for services of type `ExternalName`.

Thanks for the explanation. Supporting ExternalName services would involve creating the same frontend resources like the controller does today, but the backends will be of type - [Internet NEGs](https://cloud.google.com/load-balancing/docs/negs/setting-up-internet-negs), and the endpoint for the NEG would be the value of the externalName field in the externalName service. Correct?

**Comment by migueloller** [comment]
If the underlying resources the GCE ingress controllers uses are GCP HTTP(S) load balancers, then yes, it would set up an internet NEG with the appropriate URL map based on the ingress host and path matchers.

**Comment by smrutimandal** [comment]
[Assuming the GKE Nodepool VPC has VPN connectivity to on-prem]

Another use case is routing external traffic into internal on-prem applications by exposing e.g. a Class A IP as a service in GKE and routing the traffic through an HTTP(S) Load Balancer created by a GKE Ingress. 

Unsuccessfully tried the following manifest:

```
apiVersion: v1
kind: Endpoints
metadata:
  name: external-ip
subsets:
- addresses:
  - ip: 10.xx.xx.xx
  ports:
  - name: http
    port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: external-ip
spec:
  ports:
  - name: http
    port: 80
  type: NodePort
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: external-ip
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: external-ip
          servicePort: 80
```

As there are no pods behind this kubernetes service, currently this method shows `No pod selectors set` error in the ingress details page, creates a useless backend trying to forward the traffic at port 80 to all GKE nodes and is obviously not able to. 

Coupled with IAP, this is a low cost/tech solution to grant users external to the company, access to on-prem internal applications without explicitly granting them VPN access into the company network.

**Comment by dbacinski** [comment]
I have the same use case as @smrutimandal.

I want to give access to private hosts in local VPC (non-k8s).

My config is:
```
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: dev
spec:
  domains:
    - dev.mydomain.com
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: staging
  annotations:
    kubernetes.io/ingress.global-static-ip-name: lb-global
    networking.gke.io/managed-certificates: "dev"
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - host: dev.mydomain.com
      http:
        paths:
          - backend:
              serviceName: woo-web
              servicePort: 80
--- 
apiVersion: v1
kind: Service
metadata:
  name: woo-web
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: woo-web
  # endpoint name has to match with service name
subsets:
  - addresses:
      - ip: 10.142.0.30
    ports:
      - port: 80
        protocol: TCP
```

When I try to curl from a pod:
1. curl http://woo-web - works
2. curl http://dev.mydomain.com - returns 502
3. curl https://dev.mydomain.com - returns 502 with correct cert

In the LB logs I see:
```
jsonPayload: {
@type: "type.googleapis.com/google.cloud.loadbalancing.type.LoadBalancerLogEntry"
statusDetails: "failed_to_pick_backend"
}
```

Firewall is open to all 0.0.0.0/0

I have checked NEG created by Ingress and it is missing endpoints. When I try to add it manually on UI, nothing happens.

![neg](https://user-images.githubusercontent.com/454414/114822573-91302580-9dc2-11eb-86cd-6ab2403a7447.png)

**Comment by dbacinski** [comment]
I have switched to ingress nginx and it works without a problem.

```
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kemik-staging
  annotations:
    #https://medium.com/searce/using-multiple-google-managed-certificate-with-single-kubernetes-ingress-29c78ca4a013
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: dev.mydomain.com
      http:
        paths:
          - backend:
              serviceName: woo-web
              servicePort: 80
```

Just had to open up a firewall between nginx ingress controller pod and vpc IP (10.142.0.30)
