### ISSUE TITLE
Static ip on internal ingress

### ISSUE THREAD

**Issue by mat-613** [kubernetes/ingress-gce#1171]
Hi, I've been struggling to set static ip for my internal ingress (GCP Kubernetes with a Deployment, Service NodePort and Internal Ingress).

I'm creating this issue because I can't find a way or an annotation to specify an internal static ip to the internal ingress.

Is this currently supported?

**Comment by vitomanu96** [comment]
Mee too. Soo I am not alone.

**Comment by federico-s** [comment]
I have the same problem, I tried different ways but none of those worked for me.

**Comment by spencerhance** [comment]
Hi all,

This is not currently supported since internal ingress requires a regional static IP, but is planned for GA.  I have created a PR for this here: #1174

**Comment by spencerhance** [comment]
Hello, this should be launching in Rapid + Regular channel within the next two weeks!

**Comment by MikeMichel** [comment]
From my understanding this landed in 1.9. I tried this on a shared vpc setup and I get `Error during sync: error running load balancer syncing routine: loadbalancer 2lvxx6db-default-jenkins-lli16s90 does not exist: the given static IP name jenkins-internal-ip doesn't translate to an existing static IP.`

I am on gke `1.17.12-gke.2502` and reserved an internal IP from a host projects subnet with 
`gcloud compute addresses create jenkins-internal-ip --region europe-west1 --subnet net-devops1 --project host-project`
and referenced this in the ingress

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.gcp.kubernetes.io/pre-shared-cert: jenkins-test
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: gce-internal
    kubernetes.io/ingress.regional-static-ip-name: jenkins-internal-ip
...
```

Is this feature supposed to work with shared vpc where the internal IP is not in the same project where gke?
