### ISSUE TITLE
NEG service loses zone when single node in zone is cordoned (multi-zone node pool)

### ISSUE THREAD

**Issue by tscni** [kubernetes/ingress-gce#1183]
Configuration:
- Master version: 1.14.10-gke.36
- Cluster with 3 zones (europe-west1) and 1 node per zone (B, C, D)
- Service with NEG configuration for pod P
- Pod P is active on node D in zone europe-west1-d
-  (+ an ingress but I'll leave that out)

Trigger:
- Node D is cordoned

Effect:
- Service loses zone europe-west1-d
- Backend service loses corresponding NEG (though the NEG persists, including the relation to node D)
- Pod P is unreachable
- Service constantly receives an event like this with no visible effect:
  `Attach 1 network endpoint(s) (NEG "***" in zone "europe-west1-d")`

It seems to me this is part of the issue:
- https://github.com/kubernetes/ingress-gce/blob/74680cdb0c3d64c8d6f6a4f401e46b5da04568d5/pkg/l4/l4controller.go#L196-L199
- https://github.com/kubernetes/ingress-gce/blob/74680cdb0c3d64c8d6f6a4f401e46b5da04568d5/pkg/neg/controller.go#L626-L627
- https://github.com/kubernetes/ingress-gce/blob/74680cdb0c3d64c8d6f6a4f401e46b5da04568d5/pkg/utils/utils.go#L346-L352
I.e. the code assumes only masters are unschedulable, but all cordoned nodes, still with valid workloads, have that attribute as well.

This is a big issue with small regional clusters, which, in our case, forces us to use a single-zone node pool.

Some relevant specs:
```yaml
# node D
metadata:
  labels:
    topology.gke.io/zone: europe-west1-d
spec:
  taints:
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    timeAdded: "2020-07-15T14:23:33Z"
  unschedulable: true

# service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/neg-status: '{"network_endpoint_groups":{"8080":"***"},"zones":["europe-west1-b","europe-west1-c"]}'
```
