### ISSUE TITLE
GKE ingress stuck in `creating ingress` after deploy (master version: 	 1.15.12-gke.13)

### ISSUE THREAD

**Issue by jtestard** [kubernetes/ingress-gce#1203]
I expected the GKE ingress to deploy and pick a static IP, but it didn't. I checked, I have not reached my quota of static IPs.

Ingress definition:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tekton
  namespace: tekton-pipelines
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: tekton-dashboard
              servicePort: 9097
```

Ingress Events:
```
Events:
  Type    Reason  Age   From                     Message
  ----    ------  ----  ----                     -------
  Normal  ADD     22m   loadbalancer-controller  tekton-pipelines/tekton
```
