### ISSUE TITLE
Health check not being picked up when using internal load balancing with negs for grpc service

### ISSUE THREAD

**Issue by robertb724** [kubernetes/ingress-gce#1260]
Hi All, I am trying to setup an internal load balancer using this guide.

https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balance-ingress

When using the manifests below all of the resources are created successfully but the health check falls back to the `Default kubernetes L7 Loadbalancing health check for ILB.`

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    meta.helm.sh/release-name: thanos
    meta.helm.sh/release-namespace: observability
  labels:
  name: thanos-query-grpc
  namespace: observability
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 10901
    protocol: TCP
    targetPort: grpc
  selector:
    app.kubernetes.io/component: query
    app.kubernetes.io/instance: thanos
    app.kubernetes.io/name: thanos
  sessionAffinity: None
  type: ClusterIP
```

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: gce-internal
  name: thanos-query-neg
  namespace: observability
spec:
  backend:
    serviceName: thanos-query-grpc
    servicePort: grpc
```

I have been able to successfully follow the guide for a standard http service just by changing the `serviceName` and `servicePort` to one of the http thanos components. I did not see anything in the guide to indicate this is expected behavior.
