### ISSUE TITLE
pre-shared-cert ordering (documentation/implementation mismatch)

### ISSUE THREAD

**Issue by hermanbanken** [kubernetes/ingress-gce#1309]
The annotation `pre-shared-cert` as documented on [1] is supposed to be ordered:

> #### Which certificate is presented?
> The load balancer chooses a certificate according to these rules:
> [...]
> For pre-shared certificates listed in the annotation, the primary certificate is the first certificate in the list.

However, this is not the case. If I apply the YAML [2], then the annotation is rewritten by the controller. The last-applied annotation correctly reflects the order `cert-2, cert-1`, but the annotation becomes `cert-1,cert-2`.

This is troublesome, because some client might not support SNI. The order of the certificates in GCP Load Balancers is therefore (critically) important. We switched from Kubernetes-managed certificates to `pre-shared-certs` to more easily have the same certificates shared by multiple clusters each in their own LB. We would be able to have our Security officer deliver us a new certificate name, which we could apply to all clusters automatically using Kustomize & Flux (GitOps). However, that is impacted by this reordering bug. As a workaround, we'll need to name the primary certificate with a lexicographically-first name.

1 = https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-multi-ssl#which_certificate_is_presented is 
2 = Ingress resource
```yaml
# file: ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.gcp.kubernetes.io/pre-shared-cert: cert-2, cert-1
    kubernetes.io/ingress.allow-http: "false"
  name: services
spec:
  rules:
  - host: subdomain2.example.org
    http:
      paths:
      - backend:
          serviceName: service2
          servicePort: 80
  - host: subdomain1.example.org
    http:
      paths:
      - backend:
          serviceName: service1
          servicePort: 80
```
