### ISSUE TITLE
URLMap duplication when using host rules

### ISSUE THREAD

**Issue by Cidan** [kubernetes/ingress-gce#1324]
GKE version 1.17.12-gke.1504

Take the following Ingress as an example:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik
  annotations:
    kubernetes.io/ingress.global-static-ip-name: xxx
    networking.gke.io/managed-certificates: xxx
  labels:
    app: traefik
spec:
  backend:
    serviceName: traefik
    servicePort: web
```

This ingress works as expected and creates a single catch-all URLMap:
![image](https://user-images.githubusercontent.com/1133628/99153954-56865d80-2669-11eb-80cf-6e60275cf40d.png)

However, as soon as you add a host and path match rule:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik
  annotations:
    kubernetes.io/ingress.global-static-ip-name: xxx
    networking.gke.io/managed-certificates: xxx
  labels:
    app: traefik
spec:
  rules:
  - host: "traefik.jinked.com"
    http:
      paths:
      - path: /*
        backend:
          serviceName: traefik
          servicePort: web
  backend:
    serviceName: traefik
    servicePort: web
```

We get duplicate URLMap entries:

![image](https://user-images.githubusercontent.com/1133628/99153999-a49b6100-2669-11eb-9bca-36e1a26c9098.png)

Note that *the first host match in the image above is actually configured to point to the default backend*, and the second host match is for the actual rule in the spec. This can be verified by *setting a different default backend at the bottom of the spec* -- this will create a duplicate URLMap entry for the host, one pointing to the explicit rule, the other pointing to the default backend.

This breaks the ability to have split routing based on host to differing backends, as the GCLB will route to the first match (the default one). When manually configuring a GCLB outside of GKE, the desired behavior can be achieved by creating a backend and only sending a single host to that backend.

Let me know if I can provide any more information and feel free to reach out to me, lobato@.

Thanks!
