### ISSUE TITLE
Cloud CDN is missing multiple features in the BackendConfig

### ISSUE THREAD

**Issue by christian-roggia** [kubernetes/ingress-gce#1386]
According to the official documentation the GCE ingress only supports the basic Cloud CDN features available in GCLB:
- https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#cloud_cdn

Cloud CDN support is currently missing the following features:
- [x] Cache keys https://cloud.google.com/cdn/docs/caching#cache-keys
- [ ] Cache mode https://cloud.google.com/cdn/docs/using-cache-modes#cache-mode
- [ ] TTL https://cloud.google.com/cdn/docs/using-ttl-overrides
- [ ] Signed URLs https://cloud.google.com/cdn/docs/using-signed-urls
- [ ] Signed Cookies https://cloud.google.com/cdn/docs/using-signed-cookies
- [ ] Negative caching (beta) https://cloud.google.com/cdn/docs/using-negative-caching
- [ ] Stale content (beta) https://cloud.google.com/cdn/docs/serving-stale-content
- [ ] Bypass cache header (pre-ga) https://cloud.google.com/cdn/docs/caching#bypassing-cache

The configuration now looks like the following:
```yaml
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: my-backendconfig
spec:
  cdn:
    enabled: true
    cachePolicy:
      includeHost: ...
      includeProtocol: ...
      includeQueryString: ...
      queryStringBlacklist: ...
      queryStringWhitelist: ...
```

An expected future configuration might look like this:
```yaml
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: my-backendconfig
spec:
  cdn:
    enabled: true
    mode: FORCE_CACHE_ALL
    ttl:
      client: 60s
      default: 60s
      max: 3600s
    negativeCaching:
      enabled: true
      policies:
        - code: 403
          ttl: 60s
    requestCoalescing: true
    serveWhileStale: 60s
    signedUrls:
      enabled: true
      maxAge: 60s
      keys:
        - signed-url-key-1
        - signed-url-key-2
    bypassCacheOnRequestHeaders:
      - Bypass-Cache-Header-1
      - Bypass-Cache-Header-2
    cachePolicy:
      includeHost: ...
      includeProtocol: ...
      includeQueryString: ...
      queryStringBlacklist: ...
      queryStringWhitelist: ...
```
