### ISSUE TITLE
Ingress with GKE Autopilot has 5-6 minutes of downtime (502 errors) per deploy.

### ISSUE THREAD

**Issue by samwightt** [kubernetes/ingress-gce#1389]
I'm getting a 502 error on each deploy with GKE Autopilot for about 5-6 minutes after I trigger the deployment. It seems like the Ingress controller is removing the old pod's NEG before the new pod's health checks have all passed. [Please see here for screenshots of logs and more info](https://discuss.kubernetes.io/t/gke-http-s-ingress-returns-502-error-for-5-6-minutes-after-deploying/15274/6).

I have one instance running total, which means that Autopilot has to temporarily resize the cluster on every deploy. I'm not sure if this would contribute to it.

I've read through as much of the documentation as I can, and I can't seem to find anything relevant to this that would be causing this issue. Very disappointed that a new flagship product for GKE doesn't seem to be working properly.

Config file for the deployment:

```
apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: foundation-deployment
    spec:
      strategy:
        # Added after reading this GitHub issue: https://github.com/kubernetes/ingress-gce/issues/34#issuecomment-398831429
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 0
          maxSurge: 1
      selector:
        matchLabels:
          app: foundation-web
      template:
        metadata:
          labels:
            app: foundation-web
        spec:
          serviceAccountName: # Connects to our database account
          containers:
            # Run Cloud SQL proxy so we can safely connect to Postgres on localhost.
            - name: cloud-sql-proxy
              image: gcr.io/cloudsql-docker/gce-proxy:1.17
              resources:
                requests:
                  cpu: "250m"
                  memory: 100Mi
                limits:
                  cpu: "500m"
                  memory: 100Mi
              command:
                # Connects to Cloud SQL Proxy
              securityContext:
                runAsNonRoot: true
            - name: foundation-web
              image: # Pulls latest version of image from GCR
              imagePullPolicy: Always
              env:
               # Env-specific config
              resources:
                requests:
                  memory: "500Mi"
                  cpu: "2"
                limits:
                  memory: "1000Mi"
                  cpu: "2"
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: 4000
                initialDelaySeconds: 5
                periodSeconds: 5
              readinessProbe:
                httpGet:
                  path: /healthz
                  port: 4000
                initialDelaySeconds: 5
                periodSeconds: 5
              ports:
                - containerPort: 4000
```

Config file for the service:

```
apiVersion: v1
kind: Service
metadata:
  name: foundation-web-service
  annotations:
    cloud.google.com/backend-config: '{"ports": {"4000": "foundation-ingress-config"}}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: foundation-web
  ports:
    - port: 4000
      targetPort: 4000
```

Config file for the backend config:

```
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: foundation-ingress-config
spec:
  timeoutSec: 40
  connectionDraining:
    drainingTimeoutSec: 60
```

Config file for the ingress:

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: foundation-web-ingress
  labels:
    name: foundation-web-ingress
spec:
  backend:
    serviceName: foundation-web-service
    servicePort: 4000
```
