### ISSUE TITLE
Backend NotFound when using Elasticsearch RestHighLevelClient or ElasticsearchIO via Cloud Dataflow

### ISSUE THREAD

**Issue by dboshardy** [kubernetes/ingress-gce#1399]
As the title states, I keep getting a 404 with all routes when using the `RestHighLevelClient` or `ElasticsearchIO` in Cloud Dataflow.  I have tried the exact same routes via curl, and it works just fine.  For example:
`response 404 (backend NotFound), service rules for [ /_cluster/health ] non-existent`

Ingress config below:

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: es-ingress
  annotations:
    kubernetes.io/ingress.class: "gce-internal"
spec:
  rules:
    - host: host.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: elasticsearch-coordinating-only
              servicePort: 9200
```

Apologies if this is rather an ES issue, they do seem to share the same RestClient. However, I thought it would be worth asking here.  Both use the same `org.elasticsearch.client.RestClient` which in turn uses `org.apache.http.nio.client.CloseableHttpAsyncClient`.

 Looking at the request/packets, there are seemingly no major differences between them besides user agent and Host. The RestClient uses `host:80`. However, trying with the port in curl works fine.  Looking at the packet however, the Host header is just the hostname, whereas the RestClient sets the Host header to host:port.  Specifying "Host host.com:80" as a header replicates the error received when using the RestClient.
