### ISSUE TITLE
Backend service synchronization triggers multiple times for the same backend

### ISSUE THREAD

**Issue by gabihodoroaga** [kubernetes/ingress-gce#1447]
The backend service synchronization triggers multiple times when multiple paths use the same backend service 

For example for this configuration: 

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
spec:
  rules:
  - host: "example.com"
    http:
      paths:
      - path: /alpha
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend-service
            port:
              number: 80
      - path: /beta
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend-service
            port:
              number: 80
      # more paths here
```

the backend synchronization (health checks, cdn, iap, ...) will run for each of the paths, and each sync triggers api call to the GCE, and I assume there is a quota and rate limiting because it takes lot of time just for one backend service.
