### ISSUE TITLE
sitemap endpoint?

### ISSUE THREAD

**Issue by paOol** [kubernetes/ingress-gce#145]
when i `docker-compose up` and run my app locally, I am able to go to 
`/sitemap.xml`.
However, when I push the changes to GCE and visit the same endpoint, I try to go to 

`/sitemap.xml` and instead get sent to  `api/somethingelse/sitemap.xml`.

how do I get the correct endpoint to load?

This is my ingress file.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: example-ip
spec:
  tls:
  - hosts:
    - example.com
    secretName: example-tls
  backend:
    serviceName: example
    servicePort: 80
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: example
          servicePort: 80
```
