### ISSUE TITLE
Firewall is not configured correctly when using named ports

### ISSUE THREAD

**Issue by gabihodoroaga** [kubernetes/ingress-gce#1461]
The firewall rule that allows the traffic from the Load Balancer to the NEGs endpoints does not contain the endpoint port when a named service port is used.

For this configuration:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http
  selector:
    app: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  rules:
  - host: ""
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: nginx-service
            port:
              number: 80
```

will generate a firewall rule which allows traffic only to the node port ranges

```text
allowed:
- IPProtocol: tcp
  ports:
  - 30000-32767
...
sourceRanges:
- 35.191.0.0/16
- 130.211.0.0/22
```

as a result the health checks are failing and the load balancing is not working either.

The second issue with the firewall rule is that when the list of the ports is empty, a firewall rule is generated with protocol tcp and an empty port list.

```text
allowed:
- IPProtocol: tcp
...
sourceRanges:
- 35.191.0.0/16
- 130.211.0.0/22
```

But this means unrestricted access to any tcp port. Not ok, but not extremely bad as allows traffic only from the LB only.

The situation can be reproduced by using and invalid service name for the default backend

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  defaultBackend:
    service:
      name: nonexisting-service
      port:
        number: 80
```

I will open a pull request for these issues.
