### ISSUE TITLE
Applying backend-config annotation on existing ingress service has no effect

### ISSUE THREAD

**Issue by mikouaj** [kubernetes/ingress-gce#1503]
### Issue

Applying `cloud.google.com/backend-config` annotation on an existing service, that is associated with an existing Ingress, makes no changes on underlaying backend service.

### Use cases

* configuring CloudArmor on GKE provided default backend service, that is `default-http-backend` in `kube-system` name space
* configuring CloudArmor, IAP or other services on any existing service that is part of an Ingress but had no corresponding `BackendConfig` object

### Steps to reproduce

1. Create `Service` that matches some existing deployment
2. Create `Ingress` associated with the service created above
3. Wait until ingress is created and in sync
4. Create `BackendConfig` with Cloud Armor policy configuration *(any other configuration will apply as well)*
5. Annotate service with `cloud.google.com/backend-config` annotation pointing to `BackendConfig` created in previous step

### Expected Behavior

Cloud Armor policy is configured on a corresponding backend service 

### Actual Behavior

Nothing happens

### GKE version

`1.19.10-gke.1600`

**Comment by boredabdel** [comment]
@bowei any idea about this?

**Comment by jsravn** [comment]
Alternatively, we should be able to disable the default backend. Very few people want or are aware that ingress-gce forwards all unmatched external traffic to a pod in kube-system. This is undesirable from a security standpoint.

**Comment by bowei** [comment]
Default backend can be removed when all of the products support a 404 response instead of requiring a Pod to 404. -- however, that seems to not be related to the issue title?

**Comment by bowei** [comment]
We will take a look at this bug in the triage.

**Comment by freehan** [comment]
Does this only impact CloudArmor config or any other config in BackendConfig? 

We had a problem with CloudArmor in that version you provided and it is since fixed.

**Comment by raphaelauv** [comment]
@mikouaj I have the same problem

GKE :  1.21.5-gke.1302

**Comment by edclement** [comment]
Count me in on this problem as well...

**Comment by spencerhance** [comment]
Ack

**Comment by spencerhance** [comment]
Hi Folks, I attempted to repro this locally by adding a security policy and backendconfig to a service after the LB was provisioned but I was unable to.  If you share your redacted YAMLs or email your cluster info to the email on my profile I can take another look.

**Comment by msuterski** [comment]
@spencerhance thanks for your comment/verification. It does seem to work for default backends when they are attached to healthy Ingresses!

For future reference the steps to have the policies attached to default backends.

1. Create a security policy for the default http backend in the gcp project

    ```gcloud compute security-policies create default-http-backend```

1. Attach rule(s) to your security policy. (in this case we're attaching policy to deny all access by default and return 404)

    ```gcloud compute security-policies rules update 2147483647 --security-policy default-http-backend --action "deny-404"```

1. Create `BackendConfig` resource in the `kube-system` namespace

    ```yaml title="backend.yaml"
    # backend.yaml
    ---
    apiVersion: cloud.google.com/v1
    kind: BackendConfig
    metadata:
      name: default-http-backend
      labels:
        app.kubernetes.io/name: default-http-backend
    spec:
      timeoutSec: 40
      securityPolicy:
        name: default-http-backend
    ```

    ```kubectl apply -f backend.yaml -n kube-system```

1. Patch the default backend service to attach the required annotation

    ```yaml title="annotation.yaml"
    # annotation.yaml
    metadata:
      annotations:
        cloud.google.com/backend-config: |
          {"default":"default-http-backend"}
    ```

    ```kubectl patch service default-http-backend --patch-file annotation.yaml -n kube-system```

just FYI, this process does not work for Ingresses which backends are in an unhealthy state
