### ISSUE TITLE
load balancer frontend config disappears

### ISSUE THREAD

**Issue by nbblum** [kubernetes/ingress-gce#1558]
I'm trying to configure the frontend part of the loadbalancer to provide https. After applying the ingress configuration it works fine for a short moment and the frontend configuration is visible in the loadbalancer. But then the frontend part of the loadbalancer is not configured anymore "This load balancer has no frontend configured". 

Cluster Version: 1.20.8-gke.900

Ingress config:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-application
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "development"
    kubernetes.io/ingress.allow-http: "false"
    ingress.gcp.kubernetes.io/pre-shared-cert: "dev-test-my-application"
    networking.gke.io/v1beta1.FrontendConfig: "my-application-fe"
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: consumption-ui
            port:
              number: 80
```

output of `gcloud compute addresses list`
```
NAME              ADDRESS/RANGE   TYPE      PURPOSE  NETWORK  REGION        SUBNET  STATUS
development       1.2.3.4                  EXTERNAL                                                                     RESERVED
```

the frontend config
```
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: my-application-fe
spec:
  sslPolicy: my-policy-name
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
```

I tried it with or without a frontend config and I tried it with a secret and the tls-spec instead of the pre-shared-cert. But I can't get a stable loadbalancer running
