### ISSUE TITLE
Unknown field "logging" in com.google.cloud.v1beta1.BackendConfig.spec

### ISSUE THREAD

**Issue by caddac** [kubernetes/ingress-gce#1598]
Attempting to disable LB logging on my backend (version `cloud.google.com/v1beta1/BackendConfig`) and getting this error: ```error validating data: ValidationError(BackendConfig.spec): unknown field "logging" in com.google.cloud.v1beta1.BackendConfig.spec```

My full BackendConfig:
```
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: gke-ingress-config
spec:
  healthCheck:
    type: HTTP
    port: 15021
    requestPath: /healthz/ready
  logging:
    enable: false
```
This is being applied via FluxCD (which is reporting the error). In my cluster, the BackendConfig is actually `v1`. If I manually modify the resource, I am able to disable logging in the load balancer. I have been unable to find a doc for the `v1beta1` version. 

Any ideas what I'm doing wrong here?
