### ISSUE TITLE
[GKE] How to diagnose backend status to be Unknown

### ISSUE THREAD

**Issue by shawncao** [kubernetes/ingress-gce#1601]
Hi,

The ingress I created is pretty simple, however I can't find good clues to understand why the backend status is Uknown, and I think this is why I got `Server Error 502` from client/browser. Could you please share me some ideas how to troubleshoot it?

This is the ingress description:
```
shawncao@Shawns-MacBook-Pro columns % kubectl describe ing
Name:             columns-ingress
Namespace:        default
Address:          35.241.5.23
Default backend:  columns:8080 (<none>)
Rules:
  Host        Path  Backends
  ----        ----  --------
  *           
              /*   columns:8080 (<none>)
Annotations:  ingress.gcp.kubernetes.io/pre-shared-cert: mcrt-ac1277c5-8d37-46fc-8e40-a9692dc72323
              ingress.kubernetes.io/backends: {"k8s1-179e90eb-default-columns-8080-4cdd8a4f":"Unknown"}
```

and this is the ingress definition:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: columns-ingress
  labels:
    visibility: public
    app: columns-services
  annotations:
    # static IP: `gcloud compute addresses list`
    kubernetes.io/ingress.global-static-ip-name: varchar-io
    networking.gke.io/managed-certificates: columns-ai
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/v1beta1.FrontendConfig: "http-redirect"
spec:
  defaultBackend:
    service:
      name: columns
      port:
        number: 8080
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: columns
                port:
                  number: 8080
```

The service is running good, I tested it both from `kubectl port-forward`, as well as checking the service log which prints all correct HTTP response code 200 for readinessProbe and livenessProb:
```
10.84.0.1 - - [06/Nov/2021:02:33:15 +0000] "GET / HTTP/1.1" 200 4053 "-" "kube-probe/1.20+" "-"
10.84.0.1 - - [06/Nov/2021:02:33:25 +0000] "GET / HTTP/1.1" 200 4053 "-" "kube-probe/1.20+" "-"
10.84.0.1 - - [06/Nov/2021:02:33:30 +0000] "GET / HTTP/1.1" 200 4053 "-" "kube-probe/1.20+" "-"
10.84.0.1 - - [06/Nov/2021:02:33:35 +0000] "GET / HTTP/1.1" 200 4053 "-" "kube-probe/1.20+" "-"
10.84.0.1 - - [06/Nov/2021:02:33:45 +0000] "GET / HTTP/1.1" 200 4053 "-" "kube-probe/1.20+" "-"
10.84.0.1 - - [06/Nov/2021:02:33:50 +0000] "GET / HTTP/1.1" 200 4053 "-" "kube-probe/1.20+" "-"
```

Part of the service definition is like this:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: columns
  labels:
    app: columns-services
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: columns-services
  ports:
    - port: 8080
      name: nginx
      targetPort: 8080
```

and deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: columns-server
spec:
  selector:
    matchLabels:
      app: columns-server
  template:
    metadata:
      labels:
        app: columns-server
    spec:
      containers:
        - name: columns-nginx
          image: gcr.io/nebula-com/columns/nginx
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          ports:
            - containerPort: 8080
              hostPort: 8080
```

Many hours that I have done the search on the internet, no clear path to me, appreciate any help on this! Thanks!
