### ISSUE TITLE
Loadbalancer controller throws `Error 400: Invalid value for field 'zone': ''. `

### ISSUE THREAD

**Issue by zoeponta** [kubernetes/ingress-gce#1633]
Hello team.

I am trying v1.21.6-gke.1500.
Since upgrading to this version, Ingress has been throwing warnings.
The communication with the backend is HEALTHY, so there seems to be no problem.

Is there any problem in this situation?
Is there any way to solve it?

<details>
<summary> kubectl describe ing</summary>

```
$ kubectl describe ing -n example web
Name:             web
Namespace:        example
Address:          xx.xx.xx.xx
Default backend:  default-http-backend:80 (10.16.2.4:8080)
TLS:
  example-cert terminates replace.domain
Rules:
  Host                               Path  Backends
  ----                               ----  --------
  replace.domain  
                                     /*   web:5000 (10.16.4.99:5000)
Annotations:
  ingress.kubernetes.io/ssl-cert:               k8s2-cr-a7qpfjj2-qiosnp7e5181d65s-d3c4de2bb6cd77b6
  ingress.kubernetes.io/url-map:                k8s2-um-a7qpfjj2-example-web-k9grr75h
  kubernetes.io/ingress.allow-http:             false
  meta.helm.sh/release-name:                    web
  ingress.kubernetes.io/backends:               {"k8s-be-30676--5c4e709f46dd0587":"HEALTHY","k8s-be-31519--5c4e709f46dd0587":"HEALTHY"}
  ingress.kubernetes.io/https-forwarding-rule:  k8s2-fs-a7qpfjj2-example-web-k9grr75h
  meta.helm.sh/release-namespace:               example
  ingress.kubernetes.io/https-target-proxy:     k8s2-ts-a7qpfjj2-example-web-k9grr75h
  kubernetes.io/ingress.global-static-ip-name:  example-ip
Events:
  Type     Reason  Age                      From                     Message
  ----     ------  ----                     ----                     -------
  Normal   Sync    12m (x985 over 6d19h)    loadbalancer-controller  Scheduled for sync
  Warning  Sync    2m4s (x1588 over 6d19h)  loadbalancer-controller  Error syncing to GCP: error running backend syncing routine: googleapi: Error 400: Invalid value for field 'zone': ''. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)', invalid
```

</details>

<details>
<summary> Ingress manifest</summary>

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web
  labels:
    helm.sh/chart: web-3.0.6
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: web
    app.kubernetes.io/version: "3.0.6"
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: example-ip
spec:
  tls:
    - hosts:
      - "replace.domain"
      secretName: example-cert
  rules:
    - host: "replace.domain"
      http:
        paths:
          - path: /*
            backend:
              serviceName: web
              servicePort: 5000
```

</details>

**Comment by swetharepakula** [comment]
/kind support

Hello @zoeponta,

We have some followup questions:
* Can you provide the service manifest?
* What version was the cluster running before?
* What other changes occurred around the same time? In particular any node pool changes?
* Is this a zonal or regional cluster?
* Is the error persistent? Or did the issue eventually get resolved?

Even with the above information, this may be difficult to debug without controller logs. Please open a support ticket in GCP as support/us will have access to the controller logs and we will be able to investigate further.

Thanks!

**Comment by zoeponta** [comment]
Thanks for the reply. I'll answer your question.

> Can you provide the service manifest?

It's written in a very simple manifest using helm.

<details>
<summary> Service Manifest </summary>


```
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: example
  labels:
    helm.sh/chart: web-3.0.6
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: web
    app.kubernetes.io/version: "3.0.6"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: web
```
</details>


> What version was the cluster running before?

v1.16.15

> What other changes occurred around the same time? In particular any node pool changes?

Yes, we have changed the node pool.
I recreated it to change the machine type family from N1 to E2.

> Is this a zonal or regional cluster?

I use zonal cluster

> Is the error persistent? Or did the issue eventually get resolved?

Yes, it's still continuing.
