### ISSUE TITLE
502 Server Error

### ISSUE THREAD

**Issue by gmflau** [kubernetes/ingress-gce#164]
I managed to use External Load Balancer to allow traffic to go from public Internet to my application over HTTP (port 8888) [http://\<External-IP-from-LB\>:8888].  However, I failed to access the same application through NodePort and Ingress Controller [http://\<External-IP-from-Ingress\>/opsc].  It returned a page saying:

Error: Server Error
The server encountered a temporary error and could not complete your request.
Please try again in 30 seconds.

Here are the yamls to set up my environment:

```
apiVersion: v1
kind: Service
metadata:
  name: opscenter-nodeport
  labels:
    app: opscenter
spec:
  type: NodePort
  ports:
    - port: 8888
      name: opsc-gui-port
  selector:
    app: opscenter
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
spec:
  rules:
  - http:
      paths:
      - path: /opsc
        backend:
          serviceName: opscenter-nodeport
          servicePort: 8888
```

Any idea to share what could go wrong?  Any idea to troubleshoot the problem?
