### ISSUE TITLE
How to properly redirect www.* to proper endpoint

### ISSUE THREAD

**Issue by Scalahansolo** [kubernetes/ingress-gce#1681]
Currently on my GCE ingress, www.* does not get routed anywhere based on our configs. How do I set my ingress such that www.* get's routed to a particular service?

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: { .Values.ingressName }}
  annotations:
    kubernetes.io/ingress.class: "gce"
...
spec:
  rules: 
  - host: {{ .Values.web.host }}
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: web-service
            port:
              number: {{ .Values.web.port }}
```
