### ISSUE TITLE
Extremely slow ingress reconciliation on path and backend changes [1.22.8-gke.200]

### ISSUE THREAD

**Issue by jacek-jablonski** [kubernetes/ingress-gce#1700]
Hi,
Hope you're all doing well :).

I've got GKE cluster with more than 100 Ingress objects. Most of them were in a kind of "suspended" state, which means they pointed to services with deployments scaled to 0 replicas (staging environments ready to be instantly resumed).

I've noticed today that these ingress objects barely reacts to any changes. Changes in Load Balancer are usually applied no more than several minutes after changing ingresses. I've applied some batch changes in almost 100 of the ingresses and as for now changes in load balancer takes more than 6 hours and still not all of them are complete.

Is it possible that high amount of ingress objects may cause such a slowdown in reconciliation? Or should I look elsewhere for the cause? Is there any limit on the amount of ingress above which the controller is starting to perform worse?

**Comment by jacek-jablonski** [comment]
As an example: changes applied at 16:56
![image](https://user-images.githubusercontent.com/35669512/165161836-c2263061-0fa9-4787-9ef0-453d87cbc028.png)
This is what ingress spec looks like:
![image](https://user-images.githubusercontent.com/35669512/165161906-374d918e-abdb-4268-9527-4779f63ad113.png)
It is 21.40 and changes in Load Balancing are still not applied:
![image](https://user-images.githubusercontent.com/35669512/165162004-0d6764b8-83fb-4ea0-9030-b22b667072ba.png)

**Comment by cezarygerard** [comment]
Hi!

We are doing great, thanks for asking :-)

Could you please provide us with the cluster UUID which is to be found in the VM labels?

You can contact me via emails listed on my github profile

**Comment by jacek-jablonski** [comment]
@WillieWookiee thanks for your response. We received a similar reply from Google support. 

In our case, we combined GCE ingress and Nginx ingress in order to combine the advantages of using GLB (IAP) and the possibility of immediate changes to ingress rules enabled by Nginx ingress.

**Comment by turbo1912** [comment]
@jacek-jablonski how did you combine GCE ingress and Nginx ingress? facing similar issues and dont want to give up GCE ingress but require the flexibility of Nginx ingress

**Comment by jacek-jablonski** [comment]
Hi @turbo1912,
First you need to create service pointing to `ingress-nginx-controller`:
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/backend-config: '{"default": "staging-ingress-backend-config"}'
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    app.kubernetes.io/instance: staging-ingress
    app.kubernetes.io/name: staging-ingress
    argocd.argoproj.io/instance: staging-ingress
  name: staging-ingress
  namespace: ingress-nginx
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx-staging
    app.kubernetes.io/name: ingress-nginx
  type: ClusterIP
```

Note that in `BackendConfig` you may set up f.e. IAP. Then you create GCE ingress pointing to that service:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: staging-ingress-ip
    networking.gke.io/v1beta1.FrontendConfig: staging-ingress-frontend-config
  labels:
    app.kubernetes.io/instance: staging-ingress
    app.kubernetes.io/name: staging-ingress
    argocd.argoproj.io/instance: staging-ingress
  name: staging-ingress
  namespace: ingress-nginx
spec:
  defaultBackend:
    service:
      name: staging-ingress
      port:
        name: http
  tls:
    - hosts:
        - xxx
      secretName: staging-certs-tls
```
That shoud do the work.
