### ISSUE TITLE
BackendConfig.securityPolicy is not removed after config updates

### ISSUE THREAD

**Issue by guibirow** [kubernetes/ingress-gce#1706]
I have the following _BackendConfig_ with _securityPolicy_ that applies rate limite on a public API we expose via google load balancers. 

```
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: api
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /api/
    port: 80
  securityPolicy:
    name: rate-limit
```

The policy itself works fine to create the BackendConfig and update the Load Balancers with the desired policies, but it doesn't update ir accordingly when we remove the policy.

During releases, our team need to run performance tests against the APIs behind this policy to ensure it has not decreased performance, but unfortunatelly due to a bug in the `ingress-gce` we can't disable the policy after it is applied, causing our tests to be blocked.

I've investigated the [source code](https://github.com/kubernetes/ingress-gce/blob/37a3586364079f4af0726a0fc444135e42a56bf7/pkg/backends/features/securitypolicy.go#L35) and identified that it skips the policySetup when the `securityPolicy` is not defined.

In order to solve this issue, we need a way to either set the policy to `None` like in the ui, or it should check if a policy in the resource matches the one defined in the BackendConfig to remove it if they don't match.
