### ISSUE TITLE
Ingress not polling/syncing with Backendconfig CRD 

### ISSUE THREAD

**Issue by goobysnack** [kubernetes/ingress-gce#1744]
I have this annotation in my ingress:

`cloud.google.com/v1.BackendConfig: beconfig-helloworld-test`

and my backendconfig is:

```
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  generation: 6
  name: beconfig-helloworld-test
  namespace: default
spec:
  healthCheck:
    checkIntervalSec: 10
    healthyThreshold: 1
    port: 443
    requestPath: /foo2/index.html
    timeoutSec: 15
    type: HTTPS
    unhealthyThreshold: 2
  logging:
    enable: false
    sampleRate: 0.5
  securityPolicy:
    name: policy-helloworld-test
```

No matter what I change in the CRD, the backend service of the load balancer never updates the logging rate or the securityPolicy. 

There is not a security policy listed with 

`gcloud compute backend-services describe <be-service-name> --project=<projectID> --global` 

and the healthcheck doesn't update either.

`gcloud compute health-checks describe <hc-name> --project=<projectID>`

I've repro'd in multiple projects and ingresses in GCP/GKE.
