### ISSUE TITLE
Ingress changes resulting in 502s

### ISSUE THREAD

**Issue by trevex** [kubernetes/ingress-gce#1756]
I was recently made aware of the following behavior and am wondering if it is intentional:

When you create an `Ingress`-resource and one of the rules is changed in a way, that the service it points to is not used by the `Ingress`-resource it will result in 502s as the NEG is de-provisioned.

This can be easily reproduced on GKE Autopilot as follows:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: traefik/whoami
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: whoami
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test
spec:
  rules:
  - host: foo.mydomain.com
    http:
      paths:
      - backend:
          service:
            name: nginx
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: bar.mydomain.com
    http:
      paths:
      - backend:
          service:
            name: whoami
            port:
              number: 80
        path: /
        pathType: Prefix
```
If we change the backend of `foo.mydomain.com` above to `whoami`, `nginx` will be unused and we will get 502s for about a minute.
Unfortunately it is not possible to use a pre-existing NEGs to work around this. The only workaround is to create a "dummy"-rule to keep the NEG around and remove it later once the changes have propagates and every new request is served by the new backend.

Is this expected behavior? It would be great if the NEG is not immediately removed but kept for a few minutes to avoid 502s.
