### ISSUE TITLE
Routing for web sockets

### ISSUE THREAD

**Issue by edonnura** [kubernetes/ingress-gce#1765]
I am trying to route WebSockets requests to specific path but I am not succeeding to do that. I have an api and web application both behind the ingress, I want specific requests to go to api all others to go to web application service. WebSocket hub is hosted in api and no matter what path I add it always send requests to web application, I assume it is failing to route it correctly because of wss prefix.
WebSocket path looks like this: wss://domain.com/callHub?access_token

```
spec:
  rules:
  - host: domain.com
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: web-service
            port:
              number: 80
      - path: /api/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: api-service
            port:
              number: 80
      - path: /callHub/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: api-service
            port:
              number: 80
```
