### ISSUE TITLE
Zombie ingress keeps being created after renaming and manual deletion

### ISSUE THREAD

**Issue by PiotrDabkowski** [kubernetes/ingress-gce#1767]
I have created ingress as follows:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-1
...
```

and then pushed via `kubectl apply -f ingress.yaml`. Then after renaming the old ingress keeps being created after manual deletion. The only way to get rid seems to be via `kubectl delete -f zombie_ingress.yaml'. 

I see that in theory this is WAI, because it is hard to distinguish replacement vs new ingress creation, but it should be a bit easier to delete the zombie ingress, either via UI or otherwise. Not sure if it should be auto-created again after deletion.
