### ISSUE TITLE
Possible Regression: BackendConfig timeoutSec doesn't seem to work with GCE Ingress

### ISSUE THREAD

**Issue by sandrotanner** [kubernetes/ingress-gce#1803]
It seems the issue from #598 is back.

I am running GKE 1.24 and I cannot get timeoutSec to apply for some reason. I even deleted the ingress and created it again with no luck. 

Here is what I am doing:

Backendconfig:
```
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: backendconfig-websocket-timeout
spec:
  timeoutSec: 7200
```

ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: REDACTED
  annotations:
    [...]
    cloud.google.com/backend-config: '{"default": "backendconfig-websocket-timeout"}'
    kubernetes.io/ingress.class: "gce"
   [...]
```
What I expect: the timeout is 2h
What I get: the timeout is 30s (the default)

This issue is possibly related to #1503 ...

I will gladly provide more info if needed :)
Thanks in advance for any help
