### ISSUE TITLE
How to enable Global Access for HTTP internal load balancer? 

### ISSUE THREAD

**Issue by alexandrst88** [kubernetes/ingress-gce#1887]
Hi!, I'm trying to use gce controller with following annotations, to enable Global Access on the frontend configuration. 

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    networking.gke.io/internal-load-balancer-allow-global-access: "true"
```

```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: gce-internal
    networking.gke.io/internal-load-balancer-allow-global-access: "true"
```

from this https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balancing#service_parameters. docs, it does work for L4 LB but it doesn't for L7 internal.
