### ISSUE TITLE
What is the controller spec for an IngressClass to work with ingress-gce?

### ISSUE THREAD

**Issue by sharkymcdongles** [kubernetes/ingress-gce#1891]
As of 1.20 k8s they have introduced and recommend using the IngressClass resource to manage IngressClasses. You would create an IngressClass like this one for ingress-nginx:

```
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
spec:
  controller: k8s.io/ingress-nginx
```

On the ingress you then set the spec to contain:

`ingressClassName: ${INGRESS_CLASS}`

This is meant to take the place of the `kubernetes.io/ingress.class: nginx` annotation.

I have tried to create an IngressClass for the GCE ingress, but I can't find the spec documented anywhere for the spec.contoller setting. Does the gce ingress support this and if so what is the spec?
