### ISSUE TITLE
MultiClusterService CDN TTL configs ignored

### ISSUE THREAD

**Issue by bhidalto** [kubernetes/ingress-gce#2244]
Recently we've migrated our GKE setup to make use of MultiCluster Ingress, so we also moved our `BackendConfig` and `FrontendConfig` objects to be used within this new setup.

The migration has been smooth so far and the entire setup works as expected, however some of the CDN configs seem to reflect different values on the GCP console opposed to what we have defined on our YAML files. 

As an example, having defined the following:

```
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: {{ .Chart.Name }}
spec:
  cdn:
      enabled: true
      cachePolicy:
        includeHost: true
        includeProtocol: true
        includeQueryString: true
      clientTtl: 31622400
      defaultTtl: 31622400
      maxTtl: 31622400
      serveWhileStale: 0
  securityPolicy:
      name: "my-policy"
```

We're seeing that the CDN is enabled for the `MultiClusterIngress` but the TTL settings are using the default values:
<img width="562" alt="Screenshot 2023-08-29 at 15 22 51" src="https://github.com/kubernetes/ingress-gce/assets/17358323/1dbdd867-378c-46b1-b505-307f678f3049">

But the security policy is correctly attached and effectively working.

Reviewing the docs, on the MultiCluster [documentation](https://cloud.google.com/kubernetes-engine/docs/how-to/multi-cluster-ingress#backendconfig_support) that explains the `BackendConfig` resource, the TTL setup does not appear but on the Ingress spec [docs](https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-configuration#cloud_cdn) it does.
We've also checked that our clusters versions comply with the requirements, and the `BackendConfig` CRD is showing that all those keys exists.

At this point we believe that our `BackendConfig` YAML file is correct, but seems like the `MultiClusterService` is just ignoring the CDN specs related to the TTL and just accepting the `enabled` and `cachePolicy` keys as part of the config, which doesn't make any sense as a `MultiClusterService` object should behave as a regular Kubernetes Service.
