### ISSUE TITLE
MultiClusterService: max-rate

### ISSUE THREAD

**Issue by yellowhat** [kubernetes/ingress-gce#2282]
Hi,
I would like to manage the `max-rate-per-endpoint` via the `MultiClusterService` or `BackendConfig` k8s manifest.
Currently even if I change the "Max RPS" value for an endpoint via the console, after few minutes gets reset to the default value (100000000).

I have tried to add:

```yaml
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: name
  annotations:
    networking.gke.io/max-rate-per-endpoint: "1"
```

or 

```yaml
apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata:
  name: name
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ .Release.Name }}"}'
    networking.gke.io/max-rate-per-endpoint: "1"
```

or modifying the service created by `MultiClusterService`

 ```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"exposed_ports":{"8080":{}}}'
    cloud.google.com/neg-status: '{"network_endpoint_groups":{"5000":"..."},"zones":["us-central1-a","us-central1-c","us-central1-f"]}'
    networking.gke.io/max-rate-per-endpoint: "1"
```

But the console always shows: `Max RPS: 100000000 (per endpoint)`

Thanks
