### ISSUE TITLE
Long time-to-first-byte problem

### ISSUE THREAD

**Issue by djensen47** [kubernetes/ingress-gce#245]
I've been experiencing long wait times for time-to-first-byte (TTFB) using the ingress-gce on GKE.

I compared going through the ingress-gce versus connecting directly to a pod. Going directly to the pod via a portforward, TTFB times are in the 300ms range.

Via the ingress I have noticed:
- TTFB times between 1 - 5s
- Happens a lot on GET OPTION calls but not always
- Randomly occurs on other calls
- These are all fetch calls (ajax-style) and in a single browser reload, it happens only once

We have two rules in our configuration, three when the echoserver is up, and also tls.

I also tried this against the "echo server" and I see long >300ms TTFB on GET /favicon.ico

My best guess at reproduction is to:
- Set up a cluster
- Deploy the "echo server" gcr.io/google_containers/echoserver:1.4
- Deploy another webserver that the ingress can communicate with
- Create an ingress that has two backends and tls
- Open Chrome with developer tools open to the Network tab
- Hit the echo server
- Try this several times
- Notice that favicon.ico will very between acceptable TTFB times of <100ms to >300ms possibly even as high as 1s.

**Comment by djensen47** [comment]
Here is out ingress config:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: brewd-ingress
spec:
  tls:
  - hosts:
    - stage-api2.example.com
    - stage-app2.example.com
    - stage-echo.example.com
    secretName: redacted
  rules:
  - host: stage-api2.example.com
    http:
      paths:
      - backend:
          serviceName: gateway-service
          servicePort: 7000
  - host: stage-app2.example.com
    http:
      paths:
      - backend:
          serviceName: web-service
          servicePort: 8080
  - host: stage-echo.example.com
    http:
      paths:
        - backend:
            serviceName: echoserver
            servicePort: 8080
```

And the gateway service config (the web service is similar):

```
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels: 
    app: gateway
spec:
  type: NodePort
  ports:
  - port: 7000
  selector:
    app: gateway
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: us.gcr.io/redacted/gateway:1.3.0-rc.0
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
        env:
        - name: REDACTED_ENV
          value: stage
