### ISSUE TITLE
How to implement content-based health check for GKE ingress

### ISSUE THREAD

**Issue by raweber42** [kubernetes/ingress-gce#2468]
I want to implement a [content-based health check](https://cloud.google.com/load-balancing/docs/health-check-concepts#content-based_health_checks) for my GKE ingress. These kinds of health checks are usually specified in the BackendConfig CRD. My current BackendConfig looks like this:

```
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: XXX-hc-config
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 5
    port: 8080
    type: HTTP
    requestPath: /healthz
```
As seen in the link above, Google DOES support content-based health checks. But I cannot see, how to configure this. I expected something like:

```
healthCheck:
    checkIntervalSec: 15
    timeoutSec: 5
    port: 8080
    type: HTTP
    requestPath: /healthz
    response: "OK" <--- THIS IS NEW
```
but I cannot find anything about it. Not even in the CRD source code. Did anyone ever do this successfully? How?

In the GCP console you can set it like this:

![Screenshot 2024-02-15 at 14 40 38](https://github.com/kubernetes/ingress-gce/assets/99535319/398508f9-6942-4842-b906-905e886f0426)
