### ISSUE TITLE
Ingress health check not following ReadinessProbe

### ISSUE THREAD

**Issue by matti** [kubernetes/ingress-gce#317]
with:

```
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
```

the google health check is still `/`

Also confirmed by @Gogoro:

" When I create an ingress pointing to a service, which again points to a pod it just keeps hitting / instead of the path I defined in readinessProbe and livenessProbe. I can see in the logs that the pod itself checks itself easily, but the healthcheck goes ham on /."

In this discussion issue: https://github.com/kubernetes/ingress-gce/issues/42
