### ISSUE TITLE
GCE: WebSocket: connection is broken CloseEvent {isTrusted: true, wasClean: false, code: 1006, reason: "", type: "close", …}

### ISSUE THREAD

**Issue by bowei** [kubernetes/ingress-gce#36]
_From @unfii on August 29, 2017 13:28_

Last ingress GCE.

in ingress logs.

```
Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath   Type            Reason  Message
  ---------     --------        -----   ----                    -------------   --------        ------  -------
  58m           58m             1       loadbalancer-controller                 Normal          ADD     default/idecisiongames
  58m           58m             1       loadbalancer-controller                 Normal          ADD     default/idecisiongames
  57m           57m             1       loadbalancer-controller                 Warning         GCE     googleapi: Error 409: The resource 'projects/dm-apps-beta/global/sslCertificates/k8s-ssl-default-idecisiongames
--be0f1d8aa9717d3c' already exists, alreadyExists
  57m           57m             1       loadbalancer-controller                 Normal          CREATE  ip: 130.211.32.230
  57m           57m             1       loadbalancer-controller                 Normal          CREATE  ip: 130.211.32.230
  57m           4m              17      loadbalancer-controller                 Warning         GCE     No node tags supplied and also failed to parse the given lists of hosts for tags. Abort creating firewall rule.
```

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  labels:
    app: idg-server
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "test"
spec:
  tls:
  - secretName: test
  backend:
    serviceName: idg-server
    servicePort: 3000
```

And also default deployment from 
https://github.com/kubernetes/ingress/tree/master/examples/deployment/gce

In console we see.

`WebSocket: connection is broken CloseEvent {isTrusted: true, wasClean: false, code: 1006, reason: "", type: "close", …}`

How to fix it?

_Copied from original issue: kubernetes/ingress-nginx#1262_
