### ISSUE TITLE
unhealthy backend services, with 400, 412, 409 errors 

### ISSUE THREAD

**Issue by chaima-ennar** [kubernetes/ingress-gce#396]
I am trying to deploy an application composed of two services front and back, I am using ingress and "gce" as a controller, Every time I modify the docker image of the service ( I add modifications in the code and nothing beoyond that), the service turns to be unhealthy. and I got these errors , 

> loadbalancer-controller  received errors when updating backend service: googleapi: Error 400: The resource 'projects/fl../global/backendServices/k8s-be-32112--17c72.....ece101' is not ready, resourceNotReady
 

> loadbalancer-controller  googleapi: Error 412: Invalid fingerprint., conditionNotMet

> error 404 services already exists, 

here is my ingress ressource 

```
piVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: app
    part: ingress
  name: my-irool-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: my-ip
spec:
 backend:
    serviceName: client-svc
    servicePort: 80
 rules:
  - http:
        paths:
        - path: /back
          backend:
            serviceName: back-svc
            servicePort: 9000
  - http:
        paths:
        - path: /back/*
          backend:
            serviceName: back-svc
            servicePort: 9000
```

```

apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
    part: back
  name: back-svc
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 9000
    nodePort: 30049
    protocol: TCP
  selector:
    app: app
    part: back

```
And I the result is ? 
ingress.kubernetes.io/backends:       {"k8s-be-30049--17c7.....e101":"UNHEALTHY","k8s-be-30651--17c7......e101":"HEALTHY"}

So could you please to find the issue here ?
