### ISSUE TITLE
External CNAME records do not route properly via hostnames

### ISSUE THREAD

**Issue by buckhx** [kubernetes/ingress-gce#404]
Using CNAME records to route to services via hostnames does not work. With the following setup, dev.test.io will 404. Changing the records to both be A records in the external DNS pointing to the same static IP routes properly with the same Ingress definition.

Example Zones:
```
test.io            A              <static-ip-of-glb>
dev.test.io     CNAME    test.io 
```

Example Ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  namespace: dev 
  annotations:
    kubernetes.io/ingress.class: gce 
spec:
  tls:
  - hosts:
    - dev.test.io
    - test.io
  rules:
  - host: test.io
    http:
      paths:
      - path: /
        backend:
          serviceName: web 
          servicePort: 80
  - host: dev.test.io
    http:
      paths:
      - path: /
        backend:
          serviceName: web-dev
          servicePort: 80
```
