### ISSUE TITLE
ingress controller gave me 2 IP addresses instead of 1 when I added TLS

### ISSUE THREAD

**Issue by chrishiestand** [kubernetes/ingress-gce#410]
I was simply running the ingress on WAN port 80 and everything was working fine. Then at the same time I added a tls cert and this annotation to an ingress manifest:

```yaml
  kubernetes.io/ingress.allow-http: "false"
```
```yaml
    tls:
    - hosts:
      - mysite.com
      - www.mysite.com
      secretName: tls-mysite-com-prod
```

And now the kubernetes ingress object reports that it is listening on both ports, but in fact the original IP address only listens to port 80. When I log into the GCP console, I can see that my port 443 frontend has a different IP than the port 80 frontend.

The k8s cluster is GKE v1.10.5-gke.2.

I do not think this is supposed to happen. Email me if you want specifics (username at gmail), I don't want to publicly post the project details today.
