### ISSUE TITLE
HTTP2 health check does not use readiness probe path

### ISSUE THREAD

**Issue by anuraaga** [kubernetes/ingress-gce#487]
I recently switched some services from protocol HTTPS to HTTP2 and noticed that health checks stopped being sent to the path defined in the deployment config, but are just sent to the root path.

The deployment config is identical for 

```yaml
...
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /internal/health
            port: 8080
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /internal/health
            port: 8080
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
...
```

If svc is HTTPS, the health check uses the path
```
Description
Kubernetes L7 health check generated with readiness probe settings.

Path
/internal/health
Protocol
HTTPS
Port
31508
```

If svc is HTTP2, the health check does not
```
Description
Default kubernetes L7 Loadbalancing health check.

Protocol
HTTP2
Port
31021
```

The issue seems to be because of comparing the string `HTTP2` to `HTTPS`, as kube API does not support the scheme `HTTP2`.
