### ISSUE TITLE
Ingress controller does not support HTTP2 with mutual TLS

### ISSUE THREAD

**Issue by PassKit** [kubernetes/ingress-gce#553]
When creating an Ingress controller for a service using the `service.alpha.kubernetes.io/app-protocols: '{"grpc":"HTTP2"}'` annotation, Ingress-GCE will automatically create a HTTP2 health check to `/`.

When mutual TLS is deployed on the containers, this check will never pass, since the health check does not have access to certificates.

The following readiness probes that use [gRPC Health Probe](https://github.com/grpc-ecosystem/grpc-health-probe) are ignored by GCE.

```
readinessProbe:
  exec:
    command: ["/hc", "-addr=127.0.0.1:9999", "-tls", "-tls-ca-cert=/tls/ca-chain.pem", "-tls-client-cert=/tls/client.pem", "-tls-client-key=/tls/client-key.pem"]
  initialDelaySeconds: 
livenessProbe:
  exec:
    command: ["/hc", "-addr=127.0.0.1:9999", "-tls", "-tls-ca-cert=/tls/ca-chain.pem", "-tls-client-cert=/tls/client.pem", "-tls-client-key=/tls/client-key.pem"]
  initialDelaySeconds: 10
```
There appears to be no way to override the creation of the GCE default HTTP2 health check.
