### ISSUE TITLE
URL map / backend service mapping is totally shuffled

### ISSUE THREAD

**Issue by cdaguerre** [kubernetes/ingress-gce#555]
Hi, I have a single ingress pointing to multiple backend services with the following configuration:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: services
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ipName }}
    ingress.gcp.kubernetes.io/pre-shared-cert: {{ .Values.certificateName }}
spec:
  backend:
    serviceName: prometheus-grafana
    servicePort: 80
  rules:
  - host: grafana.{{ .Values.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: prometheus-grafana
          servicePort: 80
  - host: prometheus.{{ .Values.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: prometheus-prometheus
          servicePort: 9090
  - host: alerts.{{ .Values.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: prometheus-alertmanager
          servicePort: 9093
  - host: rabbitmq.{{ .Values.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: rabbitmq
          servicePort: 15672
  {{- if .Values.mailcatcherEnabled }}
  - host: mailcatcher.{{ .Values.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: mailcatcher
          servicePort: 80
  {{- end }}
```
These are all nodePort services with:
prometheus: 32500
alertmanager: 32501
grafana: 32502
mailcatcher: 32600
rabbitmq: 30385 

The (automatically created) GCLB mixes up the url map, see below:
<img width="645" alt="capture d ecran 2018-11-22 a 17 35 28" src="https://user-images.githubusercontent.com/4642448/48915014-70777600-ee7d-11e8-8f48-9bd002c1f4b4.png">
disclaimer: I searched the repo but didn't find any similar issues... ;)
