### ISSUE TITLE
Possible to enable OCSP stapling?

### ISSUE THREAD

**Issue by hlee-va** [kubernetes/ingress-gce#564]
We have a gce ingress configured as the front-end to serve CDN contents in our system. Everything works fine except when using firefox to visit a CDN content via HTTPS, it will complain that `MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING` because GCE ingress doesn't have OCSP stapling enabled. 

Been googling a lots but didn't find any useful answer. Is there any known workaround?
I found this commit which seems to solve the problem, but no idea how to use it. https://github.com/kubernetes/ingress-gce/commit/f6ba3abca3d99666ea7ece1b9738babba798e166

Here's our ingress yaml: 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cdn-ingress
  namespace: <<<namespace>>>
spec:
  tls:
    - secretName: cdn-wildcard-cert
  backend:
    serviceName: cdn-node-port-service
    servicePort: 80
  rules:
    - host: "*.<<our-cdn-domain>>.com"
      http:
        paths:
          - path: /*
            backend:
              serviceName: cdn-node-port-service
              servicePort: 80
```
