### ISSUE TITLE
Feature Request - Configuration via ConfigMap

### ISSUE THREAD

**Issue by olib963** [kubernetes/ingress-gce#593]
I would like to be able to inject the ingress configuration that is usually gathered from static annotations instead through a configmap. I am happy to look into implementing this myself if this would be an acceptable addition. I was hoping in the ingress I could write:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  confgMapName: ingress
  ...
```

where the configmap is

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress
data:
    kubernetes.io/ingress.global-static-ip-name: "my-ip-name"
    kubernetes.io/ingress.allow-http: "false"
```

This would allow me to reuse the same declarative Gitops repo and simply terraform a new cluster and static IP, then have terraform inject the IP name as config.
