### ISSUE TITLE
Ingress controller does not work with TCP readiness probe, defaults back to HTTP

### ISSUE THREAD

**Issue by arianitu** [kubernetes/ingress-gce#596]
I want to use a TCP readiness probe, but it keeps creating a HTTP health check **instead of a TCP health check.** In my deployment of my service, I have this:

```
        readinessProbe:
          tcpSocket:
            port: 80
            
          initialDelaySeconds: 5
          periodSeconds: 10
          
        livenessProbe:
          tcpSocket:
            port: 80
              
          initialDelaySeconds: 15
          periodSeconds: 20

        ports:
          - containerPort: 80

```

When I go to the GCE health check tab, it still uses HTTP.  Is it because I am using port 80 here?
