### ISSUE TITLE
BackendConfig timeoutSec doesn't seem to work with GCE Ingress

### ISSUE THREAD

**Issue by ConradIrwin** [kubernetes/ingress-gce#598]
I created a backendconfig object like this:

```
  apiVersion: cloud.google.com/v1beta1
  kind: BackendConfig
  metadata:
    name: mediaproxy-backend-config
  spec:
    timeoutSec: 120
    cdn:
      enabled: true
      cachePolicy:
        includeHost: true
        includeProtocol: true
        includeQueryString: true
```

and attached it to the service like this:

```
apiVersion: v1
kind: Service
metadata:
  name: mediaproxy
  labels:
    name: mediaproxy
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"8080":"mediaproxy-backend-config"}}'
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    name: mediaproxy
```

and created an ingress like this:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mediaproxy
  labels:
    name: mediaproxy
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - secretName: ingress-mediaproxy-lego
      hosts:
      - {{ .Domains.Mediaproxy }}
  backend:
    serviceName: mediaproxy
    servicePort: 8080
```

The load balancer created in my google cloud project correctly had the CDN enabled, but the timeout was still displayed as 30 seconds in the Google Cloud Console. I have since edited the timeout using the Google Cloud Console and it seems to stick with the value of 120 that I set manually.

**Comment by MrHohn** [comment]
@ConradIrwin Are you running a GKE cluster with version at or above 1.11.3-gke.18?

cc @rramkumar1

**Comment by ConradIrwin** [comment]
I'm running the default for Google Cloud, which seems to currently be `v1.10.9-gke.5`

**Comment by MrHohn** [comment]
As per https://cloud.google.com/kubernetes-engine/docs/how-to/configure-backend-service, you will need to upgrade GKE master version to >= 1.11.3-gke.18 to be able to configure timeoutSec via BackendConfig.

**Comment by ConradIrwin** [comment]
Ah, thank you, and sorry for the confusion.

**Comment by ernani** [comment]
For some reason this is not working as of GKE 1.21 either.

**Comment by sandrotanner** [comment]
I am running GKE 1.24 and I too cannot get it to apply for some reason. I even deleted the ingress and created it again with no luck. 
Are @ernani ernani and I doing something wrong or is it not working anymore?

Here is what I am doing:

Backendconfig:
```
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: backendconfig-websocket-timeout
spec:
  timeoutSec: 7200
```

ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: REDACTED
  annotations:
    [...]
    cloud.google.com/backend-config: '{"default": "backendconfig-websocket-timeout"}'
```
