### ISSUE TITLE
BackendConfig `cdn: enable: true` uses scary defaults

### ISSUE THREAD

**Issue by ConradIrwin** [kubernetes/ingress-gce#599]
I created a backend config like this:

```
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: mediaproxy-backend-config
spec:
  timeoutSec: 120
  cdn:
    enabled: true
```

Expecting it to be equivalent to the default CDN policy, which is more explicitly written like this:

```
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: mediaproxy-backend-config
spec:
  timeoutSec: 120
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: true
```

Unfortunately the default if `cachePolicy` is omitted is actually equivalent to:

```
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: mediaproxy-backend-config
spec:
  timeoutSec: 120
  cdn:
    enabled: true
    cachePolicy:
      includeHost: false
      includeProtocol: false
      includeQueryString: false
```

This is a very unsafe default, in our case query parameters are essential to prevent data leakage between users, and I would like to ask that the default be the same as the Google Cloud CDN default.

For now I can work around the problem by explicitly setting the policy, but it was a nasty surprise.
