### ISSUE TITLE
BackendConfig security policy not enforced 

### ISSUE THREAD

**Issue by jpigree** [kubernetes/ingress-gce#616]
Hi. I created a GKE cluster in version "1.11.5-gke.5" (with autoscaling activated) and I use the pre-installed gce ingress controller to expose my applications on the WAN. However, I need to **firewall** them (filtering on source IP) so I use the "security policy" field in the BackendConfig object to enforce my cloud armor policy on the load balancer. However I have a hard time making it work consistently.

Indeed, I often end up in a state where the cloud armor policy is not enforced without any change on the BackendConfig object. And actually the only steps to make it work again are to empty the "security policy" field/recreate the BackendConfig object until it works.

Here is my current configuration for a simple helloworld application:
```yaml
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: internal-http
  labels:
    app.kubernetes.io/name: "helloworld"
spec:
  securityPolicy:
    name: "<cloud armor policy name>"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app.kubernetes.io/name: "helloworld"
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "helloworld"
    spec:
      containers:
      - name: helloworld
        image: <a simple flask application answering with helloworld when receiving HTTP GET on /hello>
        ports:
          - name: http
            containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
     app.kubernetes.io/name: "helloworld"
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"http":"internal-http"}}'
spec:
  type: "NodePort"
  ports:
  - port: 5000
    name: http
  selector:
    app.kubernetes.io/name: "helloworld"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld
  labels:
    app.kubernetes.io/name: "helloworld"
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: false
    certmanager.k8s.io/cluster-issuer: letsencrypt
    kubernetes.io/tls-acme: “true”
    kubernetes.io/ingress.global-static-ip-name: "<the static reserved ip name>"
spec:
  tls:
  - hosts:
    - <helloworld fqdn>
    secretName: <secret containing Letsencrypt certificate>
  rules:
  - host: <helloworld fqdn>
    http:
      paths:
      - path: /hello
        backend:
          serviceName: helloworld
          servicePort: 5000
```

This configuration stopped working when I recreated my cluster and reapplied my manifests. I think this is due to my recreation, because I did it with terraform which didn't emptied the "securityPolicy" field of the BackendConfig object before deletion. Is this the expected behaviour though? What can I do to recover when this happens?

When debugging, I saw that describing the backendconfig object does not tell the state of the load balancer. Is there another way of getting those informations?

Finally, I am a bit scared to use the BackendConfig to firewall my services right now, because it can potentially expose my services to the WAN even if my desired state explicitly tells otherwise without throwing an error.

I will gladly take advices here. Thanks for your help.
