### ISSUE TITLE
How to expose ports

### ISSUE THREAD

**Issue by domcar** [kubernetes/ingress-gce#634]
Hi,

I wonder how I can open tcp ports with ingress-gce.
To be clear, I used until now nginx-controller and I used to  create a configmap, for example:
```
apiVersion: v1
data:
  "22": gitlab/gitlab-gitlab-shell:22
kind: ConfigMap
metadata:
  name: gitlab-nginx-ingress-tcp
  namespace: gitlab
```
With this configmap I can use port 22 on my gitlab deployment.

How can I achieve the same with gce-ingress?
If the same question was already answered or if there is a tutorial I can follow, could you please point me to it?

Thanks for the help!
