### ISSUE TITLE
If readiness probe is on port different than the service (app) port - ingress failes to sync the correct healthcheck

### ISSUE THREAD

**Issue by iftachsc** [kubernetes/ingress-gce#647]
I have a deployment that its healthcheck is running on different port than the app port (80).
our Ingress resource creates a HTTP loadbalancer with HTTP healthcheck on the root path (/)-  on the NodePort exposing the service port 80. 

the service has definition of the healtcheck port (in addition to the app port) and also the deployment has it, including containerPort field. the pod is healthy and apears under Endpoints.

in order to make sure this is the issue, changing the readinessProbe port to the serving port and recreating ingress yielded the correct healthcheck, reading the correct path this time (/healthz/ready)

this is a big issue for us. that actually convinces us to let go HTTP LB and go TCP LB because we dont want to manually create the HTTP LB risking connectivity loss if instance groups change underneath.

**Comment by rramkumar1** [comment]
@iftachsc Just for clarify, could post full YAML's of your Ingress, Service and Deployment?

**Comment by rramkumar1** [comment]
Looks like there are some gaps in our documentation [1] for this that don't make it clear what port your health checks should be on. I will take an AI to update the docs.

[1] https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#health_checks

**Comment by nicktrav** [comment]
Just dropping in to say that we hit this today too and consider it more of a limitation of the controller rather than a gap of documentation.

For completeness, we also have a healthcheck running on a separate port to the container port that serves up the main traffic for the pod. Right now it seems like the controller doesn't distinguish between healthcheck and non-healthcheck traffic.

If the NodePort service proxies to a container port that isn't associated with the livenessProbe, the healthcheck is created for `/` (which in our case doesn't exist, so the healthchecks don't pass). If the NodePort service proxies to the healthcheck port, then all that's exposed externally is the healthcheck.

Happy opening a separate ticket as a more formal feature request if that's easier.

**Comment by rramkumar1** [comment]
@nicktrav I agree that ideally, we should be able to create a health check that points to the healthcheck port for an application. However, there is no robust way for the controller to know which port is the healthcheck port for an application. 

Do you mind posting your YAML's? Might be easier to explain with a concret example.

**Comment by nicktrav** [comment]
Here's a minimal example:

`config-map.yaml`:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        server {
            listen       1111;
            server_name  localhost;

            location /foo {
                return 200;
            }
        }

        server {
            listen       2222;
            server_name  localhost;

            location /healthz {
                return 200;
            }
        }
    }
```

`deployment.yaml`:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15
        command: [ "nginx" ]
        args: [ "-g", "daemon off;", "-c", "/etc/config/nginx.conf" ]
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthcheck
        readinessProbe:
          httpGet:
            path: /healthz
            port: healthcheck
        ports:
        - containerPort: 1111
          name: http
        - containerPort: 2222
          name: healthcheck
        volumeMounts:
        - name: nginx
          mountPath: /etc/config
      volumes:
      - name: nginx
        configMap:
          name: nginx
```

`service.yaml`:
```yaml
kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: http
  - name: healthcheck
    protocol: TCP
    port: 8081
    targetPort: healthcheck
```

`ingress.yaml`:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - http:
      paths:
      - path: /foo
        backend:
          serviceName: nginx
          servicePort: 8081
```

With this setup, the `Ingress` is created with a healthcheck pointed at `/healthz` on the healthcheck port on the container (which only responds to that route, no others). Changing the `servicePort` to `8080` results in the healthcheck pointed at `/` on the non-healthcheck port on the container (which doesn't respond to that route, only `/foo`, which is the route in the `Ingress`).

I understand what's going on, and I realize it's more of a limitation of `Ingress`, rather than the GCE controller. That said, right now there is a link between the `Ingress` and the `Pod`s, as the GCE controller is able to use the `servicePort` to infer (transitively) what the healthcheck route should be based on the readiness probe's `httpGet` path.

This does feel like a legitimate use-case though (i.e. having fine-grained control and decoupling of the healthcheck port from the main port on which traffic is served). Maybe this is a better conversation for one of the main k8s issue trackers?
