### ISSUE TITLE
Cannot Disable HTTP when using managed-certificates. Results in infinite Creating ingress and 'no frontend configuration' 

### ISSUE THREAD

**Issue by jakebolam** [kubernetes/ingress-gce#738]
Cannot Disable HTTP when using managed-certificates

When specifying the flag `kubernetes.io/ingress.allow-http: "false"` the ingress is never created, remains stuck in _Creating ingress_. Removing this annotation successfully completes the creation.

### Versions
Kubernetes master/node-kube version: `1.12.6-gke.10`

### Additional Details:
The load balancer has the error `This load balancer has no frontend configured`
Hitting the HTTPS gateway results in `unexpectedly closed the connection.`
Hitting the HTTP gateway results in a google engine error page.

### Configuration
```
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: api-certifcate
spec:
  domains:
    - example.com
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: "web-static-ip"
    networking.gke.io/managed-certificates: api-certifcate
spec:
  rules:
    - http:
        paths:
          - path: /my-service/*
            backend:
              serviceName: my-service
              servicePort: 8080
```
