### ISSUE TITLE
Invalid value for field 'namedPorts[*].port': '0'

### ISSUE THREAD

**Issue by stevenbarragan** [kubernetes/ingress-gce#75]
```
googleapi: Error 400: Invalid value for field 'namedPorts[12].port': '0'. Must be greater than or equal to 1, invalid
```

All ingress already created still work, besides the error, but when I create a new one, I get the same error and the new one doesn't work.

I'm not exactly sure what triggered it, but I updated to 1.8.2 recently.

This is my ingress
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.gcp.kubernetes.io/pre-shared-cert: star-versussystems-com
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: coreserver-sdk-develop
  creationTimestamp: 2017-11-09T18:36:40Z
  generation: 1
  labels:
    app: coreserver
    chart: coreserver-0.1.0
    heritage: Tiller
    release: coreserver-sdk-develop
  name: coreserver-sdk-develop
  namespace: develop
  resourceVersion: "11786409"
  selfLink: /apis/extensions/v1beta1/namespaces/develop/ingresses/coreserver-sdk-develop
  uid: ######
spec:
  backend:
    serviceName: coreserver-sdk-develop
    servicePort: 80
  rules:
  - host: coreserver-sdk-develop.versussystems.com
    http:
      paths:
      - backend:
          serviceName: coreserver-sdk-develop
          servicePort: 80
status:
  loadBalancer: {}
```

Any ideas?

**Comment by nicksardo** [comment]
You probably have an ingress referencing a service that's not type NodePort. It may not be the newly added ingress, it could be any GCE ingress.

**Comment by rayfoss** [comment]
I was able to solve it by adding an annotation to disable the Google LB for my ingress.
```
metadata:
  name: test-deployment
  annotations:
    kubernetes.io/ingress.class: "nginx"
```

http://blog.chronos-technology.nl/post/disabling-gke-load-balancer-in-kubernetes/

**Comment by ddehghan** [comment]
Yes.     kubernetes.io/ingress.class: nginx can handle services that are exposed by ClusterIp.  We have it working in production

**Comment by rayfoss** [comment]
@ddehghan I definitely tried that in GKE with no luck, I'm having to use a dynamic IP on a node, which changes every k8s update. Are you sure you're using cluster ip and not node ip?

**Comment by ddehghan** [comment]
Here is my settings. nginx-ingress-controller is deployed in the cluster and gets the traffic from the External Load balancer on GKE.  We dont expose our pods to the GCE ingress. We just use it to bring the traffic to our own nginx-ingress. With the settings below the traffic gets routed correctly. But we still see this error 

> "googleapi: Error 400: Invalid value for field 'namedPorts[4].port': '0'. Must be greater than or equal to 1, invalid"

I am pretty sure this is just a bug. I deleted the ingress and recreated it and the error went away.
It actually happens consistently. I changed the service type form Nodeport to ClusterIP and back and the errors appears. And I deleted the ingress and recreated it and the error goes away.

```
---
Not shown is the nginx-ingress-controller deployed with helm.
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:

  name: https-ingress

  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod-cluster-issuer
spec:

  tls:
  - secretName: example-prod-tls
    hosts:
    - example.io
    - '*.example.io'

  rules:

  - host: test2.example.io
    http:
      paths:
      - path: /
        backend:
          serviceName: dm-django-stage
          servicePort: dm-django-port
---
apiVersion: v1
kind: Service
metadata:
  name: dm-django-stage
spec:
  ports:
  - name: dm-django-port
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: dm-django
  type: NodePort            <--  or ClusterIP here. They both work.



```
