### ISSUE TITLE
ingress path confusing

### ISSUE THREAD

**Issue by mikepc** [kubernetes/ingress-gce#76]
paths:
      - path: /posts/*
        backend:
          serviceName: post-service
          servicePort: 8585

Requests to /posts are sent to the default backend (404!), while sub-path requests are forwarded accordingly.

There needs to be sufficient documentation around this so that we know how to configure the ingress forwarding. I've tried adding 2 separate paths one for /posts, and /posts/* and that didn't work either.

How can I send all requests for /posts to my post-service backend?

**Comment by nicksardo** [comment]
```
...
  rules:
  - http:
      paths:
      - backend:
          serviceName: my-echo-svc
          servicePort: my-http-port
        path: /http
      - backend:
          serviceName: my-echo-svc
          servicePort: my-http-port
        path: /http/*
```

yielded this in GCP Console which is consistent with their documentation: https://cloud.google.com/compute/docs/load-balancing/http/url-map
![GCP Console](https://i.imgur.com/jboiZQg.png)
