### ISSUE TITLE
Cannot Disable HTTP when using managed-certificates. HTTPS + HTTP are both provisioned

### ISSUE THREAD

**Issue by jakebolam** [kubernetes/ingress-gce#764]
Cannot disable HTTP when using managed-certificates

When specifying the annotation `kubernetes.io/ingress.allow-http: "false"` the ingress still accepts HTTP traffic. 

### Versions
Kubernetes master/node-kube version: `1.12.7-gke.17` (Note: must be equal to or greater than this version, managed certificates had issues prior to this version see https://github.com/GoogleCloudPlatform/gke-managed-certs/issues/2)

### Additional Details:
I also tried (https://github.com/kubernetes/ingress-gce/issues/738#issuecomment-486738549):
1. Creating an ingress without `kubernetes.io/ingress.allow-http: "false"`.
2. Verified the ingress was serving HTTPS
3. Then setting `allow-http to "false"` 

### Configuration
```
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: api-certifcate
spec:
  domains:
    - example.com
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: "web-static-ip"
    networking.gke.io/managed-certificates: api-certifcate
spec:
  rules:
    - http:
        paths:
          - path: /my-service/*
            backend:
              serviceName: my-service
              servicePort: 8080
```

**Comment by jakebolam** [comment]
This was previously reported, but the issue was masked by issues in managed-certificates up until recent versions. See https://github.com/kubernetes/ingress-gce/issues/738

**Comment by jakebolam** [comment]
Debugging config from provisioned ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.gcp.kubernetes.io/pre-shared-cert: xxxxxx, xxxxx, xxxx
    ingress.kubernetes.io/backends: '{"xxxx":"HEALTHY","xxxx":"HEALTHY"}'
    ingress.kubernetes.io/forwarding-rule: xxxx
    ingress.kubernetes.io/https-forwarding-rule: xxxxx
    ingress.kubernetes.io/https-target-proxy: xxxxx
    ingress.kubernetes.io/ssl-cert: xxxxxxxx, xxxxxx, xxxx
    ingress.kubernetes.io/target-proxy: xxxxx
    ingress.kubernetes.io/url-map: xxxxxx
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: web-static-ip
    networking.gke.io/managed-certificates: api-certifcate
  creationTimestamp: 2019-05-23T21:54:39Z
  generation: 2
  name: my-ingress
  namespace: default
  resourceVersion: "2986739"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/my-ingress
  uid:xxxxxx
spec:
  rules:
    - http:
        paths:
          - path: /my-service/*
            backend:
              serviceName: my-service
              servicePort: 8080
status:
  loadBalancer:
    ingress:
    - ip: xxx.xxx.xxx.xx
```

**Comment by rramkumar1** [comment]
@jakebolam Ok, now I think you have discovered the bug. Turns out, we knew about this and were fixing it (#631) but the PR stalled a bit. I actually thought this PR was merged a while back and as a result I gave you the wrong advice in #738 (regarding adding the annotation after the frontend was configured) so apologies for that. 

/assign

**Comment by rramkumar1** [comment]
@jakebolam A potential workaround might be to delete the HTTP resources manually until we can ship the fix.

**Comment by jakebolam** [comment]
no worries, thanks for replying so fast. Looking forward to the PR getting merged.

Will do :)

**Comment by AlienResidents** [comment]
Hi,

I'm also looking forward to getting PR #631 merged.  Any update on that stalled PR?


Chris-

**Comment by bowei** [comment]
BTW : We are looking at fixing the issue in #631 not on that specific PR.

**Comment by bshibs** [comment]
Just to confirm: manually deleting the LB Frontend port/protocol is a viable workaround until the fix lands?

**Comment by svachmic** [comment]
Could be related to this:
https://issuetracker.google.com/issues/35904733

Any signs that it will finally be resolved?

**Comment by roobert** [comment]
I'm also seeing this issue with GKE `1.14.10-gke.17`.

Since it's not yet possible to redirect http->https (https://issuetracker.google.com/issues/35904733) and this annotation doesn't work when using GCP managed certificates, there doesn't appear to be a good way to easily disable the HTTP port left open by the GKE ingress controller.

**Comment by Setheck** [comment]
Unable to disable HTTP via annotation `kubernetes.io/ingress.allow-http: "false"` on 1.15.9-gke.12 
Hoping for http->https rewrite :crossed_fingers: 
But should this issue be re-opened?

**Comment by pgp** [comment]
I think this should be solved as soon as possible, it's a real shame a security issue of this size is still open... Even without rewrite, disabling http completely should suffice at least for most restricted scenarios

**Comment by svachmic** [comment]
[Quoting a Googler](https://issuetracker.google.com/issues/35904733#comment93) from the parent issue in Google's bug tracker I quoted:

> We have an Alpha available for HTTP(S) Load Balancing URL Rewrites and Redirects.  All Alpha terms apply. You need to be white-listed for the alpha. Please contact your Sales Representative or Account Team for more information. 
>
> We are proactively working on collecting feedback for the Alpha and will then open it up for public use without any white-listing.

Help is on its way, unfortunately I am not white-listed and cannot provide any feedback for how good/bad the solution is. If anybody is, please let us know **anything that an alpha NDA allows you to**.

**Comment by jmound** [comment]
@jakebolam Feel free to reopen it, I don't think this issue should be closed.

**Comment by svachmic** [comment]
The 5year old underlying issue seems to [have been resolved](https://issuetracker.google.com/issues/35904733#comment95). 

The question is - correctly asked as the next comment in the issue tracker - how can we make this work in GKE?

**Comment by jmound** [comment]
@rramkumar1 Are you able to reopen this issue? If not, should a new one be opened?

**Comment by rramkumar1** [comment]
@jmound Let me refresh myself on what the exact issue was here and get back to you. Thanks.

**Comment by rramkumar1** [comment]
@jmound So there are a couple things to unpack here:

1. The underlying issue that caused this issue to be filed has been fixed in #631. If you are not observing that the fix is working, then we can keep this open but otherwise this issue should be closed.
2. Support for SSL-redirects in GKE Ingress is being tracked in #1075 and we will be providing updates on that issue.

Hope that helps.

**Comment by skmatti** [comment]
The fix(#894) is available in GKE version v1.16.4-gke.25 and above(or Ingress v1.8.2).

**Comment by pgp** [comment]
Hi, just tried this fix (allowHttp: false) with cluster version 1.17.5-gke.0
It actually works, in the sense that when I try to send a plain HTTP request, the response is a 404 from GCP backend. Anyway, with this strategy, any sensitive content in a plain HTTP request is actually sent over the internet (e.g. the body of a POST request); I rather expected the server to deny the TCP handshake - i.e. respond immediately with a Connection Reset, in so preventing sending data over the network at all. Do you believe such an improvement is possible?

**Comment by rramkumar1** [comment]
@pgp I think the HTTPS redirects feature is what you are after. See #1075

**Comment by pgp** [comment]
No, in terms of actual security, http->https redirect is equivalent to the situation I described above, in that my plain HTTP request travels over the network, even if it shouldn't (the only difference is I receive a 302 response instead of a 404 one, but the concept is the same). Completely blocking the traffic on port 80 can be useful in case some REST API users do not comply with the given specifications (i.e. they deliberately or erroneously use http instead of https for an endpoint). Clearly, the steady-state situation is the same - a user receiving a 404 response will modify its client calls accordingly - but meanwhile some (possibly sensitive or private) data have been travelling in plaintext over the public internet.

**Comment by rramkumar1** [comment]
@pgp I see, thanks for the clarification. I'll bring this up with our load balancing teams to see if there is a feature request here. Until this sort of feature is supported in the upstream load balancing API there is nothing we can do here.

**Comment by rramkumar1** [comment]
@pgp Found https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security. Not sure if it helps in your case.

**Comment by pgp** [comment]
That always regards the response a server sends, nothing prevents the client from sending any kind of data in plain text before knowing this... Anyway, I'll look for possible updates on this issue, thanks for now.

**Comment by Andrewangeta** [comment]
I'm also facing this issue on the latest version and I'm losing my mind.

**Comment by Andrewangeta** [comment]
my hydrated yaml looks like this and the cert tries to create itself and every time it just ends up saying `FAILED_NOT_VISIBLE` after about 15 minutes of `PROVISIONING`
```yaml
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: my-app-certificate
  namespace: my-app
spec:
  domains:
  - my.domain
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: my-app-static-ip
    networking.gke.io/managed-certificates: my-app-certificate
  name: my-app-ingress
  namespace: my-app-dev
spec:
  backend:
    serviceName: my-app
    servicePort: 80
```
