### ISSUE TITLE
GKE: IAP > L7 > custom host and path rules > Error code 11

### ISSUE THREAD

**Issue by SaadBinShahid** [kubernetes/ingress-gce#765]
**What happened**:

I am using GKE Identity-aware proxy > L7 load balancer > Custom host and path rules. It works fine for the root-path. But it does not work for custom paths.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "my-static-ip"
spec:
  rules:
  - host: my.custom.org
    http:
      paths:
      - path: /v1/*
        backend:
          serviceName: webv1
          servicePort: 8080
      - path: /v3/*
        backend:
          serviceName: webv3
          servicePort: 8080
      - path: /nginx/*
        backend:
          serviceName: nginx
          servicePort: 80
      - path: /*
        backend:
          serviceName: nginx
          servicePort: 80
```

**What you expected to happen**:

Path `/` and `/nginx/` works fine. `/v2/` and `/v3/` throws `There was a problem with your request. Error code 11`.

If I disable the IAP, everything works fine.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.7-gke.17
- Cloud provider or hardware configuration: GKE

Setting up HTTP Load Balancing with Ingress @ https://cloud.google.com/kubernetes-engine/docs/tutorials/http-balancer
Enabling Cloud IAP for GKE @ https://cloud.google.com/iap/docs/enabling-kubernetes-howto

Stackoverflow @ https://stackoverflow.com/questions/56340775/gke-identity-aware-proxy-l7-load-balancer-custom-host-and-path-rules-erro
Google Issue Tracker @ https://issuetracker.google.com/issues/134037406
