### ISSUE TITLE
failureThreshold of readinessProbe is not reflected to health check

### ISSUE THREAD

**Issue by sonots** [kubernetes/ingress-gce#771]
With readinessProbe such as:

```
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 4
          successThreshold: 1
          failureThreshold: 3
```

A health check was created as:

![image](https://user-images.githubusercontent.com/2290461/59458165-e44a9180-8e54-11e9-9744-fcefcccf86c4.png)

It seems that `failureThreshold` is not reflected to `unhealthy threshold` at

https://github.com/kubernetes/ingress-gce/blob/e50d26db3545c986373ea591e308225ad9ec4e19/pkg/backends/syncer.go#L224-L249
