### ISSUE TITLE
health check interval adds 60sec from periodSeconds of readinessProbe unexpectedly

### ISSUE THREAD

**Issue by sonots** [kubernetes/ingress-gce#772]
With readinessProbe such as:

```
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 4
          successThreshold: 1
          failureThreshold: 3
```

A health check was created as:

![image](https://user-images.githubusercontent.com/2290461/59458165-e44a9180-8e54-11e9-9744-fcefcccf86c4.png)

Note that the `check interval` is configured as 65 sec, not 5 sec.
