### ISSUE TITLE
Source IP only contains ISP address & ephemeral address

### ISSUE THREAD

**Issue by ItsLeeOwen** [kubernetes/ingress-gce#775]
I'm hoping to at least ascertain whether a service exposed via an ephemeral address, GLB using HTTP Protocol, created from the Ingress manifest is capable of including a user's originating source/client IP in the `X-Forwarded-For` header when accessed directly by the ephemeral address.  Any direction, or suggestions are appreciated.

I have a go service that uses the client/source IP address of my user, which works when hosted outside of GKE.  When deployed on GKE cluster 1.13.6-gke.6 with an Ingress the `X-Forwarded-For` header only contains an IP address for the Internet Service Provider (ATT, Spectrum, etc), followed by the GCP ephemeral ip address, lacking the originating client IP. 

I'm struggling to find similar issues experienced by others, or info that might help me understand why the header doesn't also include the client IP.

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ip-ingress
  labels:
    app: ip-ingress
  annotations:
    cloud.google.com/app-protocols: '{"ip":"HTTP"}'
spec:
  backend:
    serviceName: ip
    servicePort: 80
```
```yaml
apiVersion: v1
kind: Service
metadata:
  name: ip
  annotations:
    service.beta.kubernetes.io/external-traffic: OnlyLocal
spec:
  type: NodePort
  externalTrafficPolicy: Local
  sessionAffinity: ClientIP
  ports:
  - name: http
    targetPort: 80
    port: 80
```
