### ISSUE TITLE
Duplicate rules created in load balancer

### ISSUE THREAD

**Issue by gijo-varghese** [kubernetes/ingress-gce#821]
Every time I add a new rule to the ingress, it creates multiple rules in the load balancer. The rules are basically the same, pointing to the same backend

Here is my ingress file:
```yaml
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: ingress-test.wpspeedmatters.com
spec:
  domains:
    - ingress-test.wpspeedmatters.com
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: wordpress-ip
    networking.gke.io/managed-certificates: ingress-test.wpspeedmatters.com
spec:
  backend:
    serviceName: wordpress
    servicePort: 8080
  rules:
    - host: ingress-test.wpspeedmatters.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: wordpress
              servicePort: 8080
```

Here are the duplicate rules created in the load balancer:
![AwesomeScreenshot-console-cloud-google-net-services-loadbalancing-details-http-k8s-um-default-basic-ingress--6dca0e07f90e8063-2019-08-10_8_53](https://user-images.githubusercontent.com/23092846/62816950-589b6b80-bb4c-11e9-9670-28b14eade408.png)

**Comment by rramkumar1** [comment]
@gijo-varghese Nothing about your Ingress spec stands out, it looks pretty normal...

Can you dump the contents of the url map k8s-um-default-basic-ingress--6dca0e07f... via the gcloud command line tool? I want to see if the output JSON also has duplicate rules. This would rule out some sort of UI issue.

**Comment by gijo-varghese** [comment]
@rramkumar1 here is the dump of a similar load balancer:
```
creationTimestamp: '2019-08-11T07:05:44.900-07:00'
defaultService: https://www.googleapis.com/compute/v1/projects/messengerify-test/global/backendServices/k8s-be-32748--6ec2919d9eb52b04
fingerprint: vkwPEy0akm4=
hostRules:
- hosts:
  - test-one.wpspeedmatters.com
  pathMatcher: hostdcdca3d119ea4935b7ac809d619cb470
- hosts:
  - test-two.wpspeedmatters.com
  pathMatcher: host3ceb073eb7b244992ec05cfec239fc09
id: '8242956804984512087'
kind: compute#urlMap
name: k8s-um-default-basic-ingress--6ec2919d9eb52b04
pathMatchers:
- defaultService: https://www.googleapis.com/compute/v1/projects/messengerify-test/global/backendServices/k8s-be-32748--6ec2919d9eb52b04
  name: hostdcdca3d119ea4935b7ac809d619cb470
  pathRules:
  - paths:
    - /*
    service: https://www.googleapis.com/compute/v1/projects/messengerify-test/global/backendServices/k8s-be-32748--6ec2919d9eb52b04
- defaultService: https://www.googleapis.com/compute/v1/projects/messengerify-test/global/backendServices/k8s-be-32748--6ec2919d9eb52b04
  name: host3ceb073eb7b244992ec05cfec239fc09
  pathRules:
  - paths:
    - /*
    service: https://www.googleapis.com/compute/v1/projects/messengerify-test/global/backendServices/k8s-be-32748--6ec2919d9eb52b04
selfLink: https://www.googleapis.com/compute/v1/projects/messengerify-test/global/urlMaps/k8s-um-default-basic-ingress--6ec2919d9eb52b04
```
