### ISSUE TITLE
GCE Ingress creates a Network Endpoint Group with 0 configured

### ISSUE THREAD

**Issue by giladsh1** [kubernetes/ingress-gce#832]
GCE Ingress creates a network endpoint group with 0 configured, when setting targetPort name instead of the actual number.
This config will not work and will essentially create a useless network endpoint group, which doesn't recognise the pods.
```
apiVersion: v1
kind: Service
metadata:
  name: mgmt
  namespace: riscale-test
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    beta.cloud.google.com/backend-config: '{"ports": {"8080":"mgmt-service-backend"}}'
spec:
  selector:
    app: mgmt
  type: NodePort
  ports:
    - port: 8080
      targetPort: mgmt-port
      protocol: TCP
```

However, when changing the `targetPort` to 8080, the network endpoint group will recognise the running pods.
This was a tough bug to catch :-(

**Comment by giladsh1** [comment]
@rramkumar1 adding the deployment config as requested - 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mgmt
  namespace: riscale-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mgmt
  template:
    metadata:
      labels:
        app: mgmt
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-nodepool
                    operator: In
                    values:
                      - default-pool
      restartPolicy: Always
      containers:
        - name: mgmt
          image: eu.gcr.io/riscale/mgmt
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 10Mi
            limits:
              cpu: 150m
              memory: 50Mi
          ports:
            - name: mgmt-port
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /m/health
              port: mgmt-port
            initialDelaySeconds: 2
            periodSeconds: 15
            successThreshold: 2
            failureThreshold: 4
          livenessProbe:
            httpGet:
              path: /m/health
              port: mgmt-port
            periodSeconds: 15
            failureThreshold: 4
          envFrom:
            - configMapRef:
                name: common-config
            - configMapRef:
                name: service-discovery
            - configMapRef:
                name: postgres-config
            - configMapRef:
                name: mongo-config
            - secretRef:
                name: rethinkdb-secrets
            - secretRef:
                name: postgres-secrets
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/mgmt-kms-encrypt.json
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
              readOnly: true
      volumes:
        - name: google-cloud-key
          secret:
            secretName: mgmt-kms-encrypt-secret
```

**Comment by axot** [comment]
We are suffering exactly same issue.

**Comment by axot** [comment]
After changing targetPort to port number, ingress works now, but we found PODs in a zone never get ready, we deployed our PODs in a,b,c zone, in this case, b zone POD got the issue.

```
$ kgp -o wide
NAME                       READY   STATUS    RESTARTS   AGE     IP             NODE                                                  NOMINATED NODE   READINESS GATES
haproxy-56f8cbc54f-96vqh   1/1     Running   0          4h36m   10.123.131.3   gke-done-production-proxy-1-haproxy-0-4ea1ef33-r08b   <none>           1/1
haproxy-56f8cbc54f-vt2c8   1/1     Running   0          52m     10.123.129.6   gke-done-production-proxy-1-haproxy-0-ec94ed76-hpkn   <none>           1/1
haproxy-67d4497588-8rtdr   1/1     Running   0          12m     10.123.140.3   gke-done-production-proxy-1-haproxy-0-ec94ed76-q2zw   <none>           1/1
haproxy-67d4497588-tg9zt   1/1     Running   0          12m     10.123.141.2   gke-done-production-proxy-1-haproxy-0-97c8c492-949s   <none>           0/1
```

**Comment by freehan** [comment]
adding a fix and e2e test to prevent regression.

**Comment by freehan** [comment]
Okay. I think I uncover the problem. This is actually a bug in endpoints controller. 

Here is my test yamls:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: hostname
  name: hostname
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: hostname
    spec:
      containers:
      - image: gcr.io/google_containers/serve-hostname-amd64:1.5
        imagePullPolicy: IfNotPresent
        name: hostname
        readinessProbe:
          failureThreshold: 3
          httpGet:
           path: /readiness
           port: namedport
           scheme: HTTP
        ports:
        - name: namedport
          containerPort: 9376
---
apiVersion: v1
kind: Service
metadata:
  name: hostname
  namespace: default
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: namedport
  selector:
    run: hostname
  sessionAffinity: None
```

In this case, endpoints controller will create the following endpoints object:
```
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
  name: hostname
  namespace: default
subsets:
- addresses:
  - ip: 10.56.2.6
    targetRef:
      kind: Pod
      name: hostname-8548b8d795-8mdxz
      namespace: default
      resourceVersion: "2766744"
      uid: ff6bb29c-dbf6-11e9-a197-42010a800098
  ports:
  - port: 9376
    protocol: TCP

```
