### ISSUE TITLE
Allow more than 50 paths routes per domain

### ISSUE THREAD

**Issue by mafraba** [kubernetes/ingress-gce#837]
Currently it doesn't seem possible to setup more than 50 paths for a given host rule in an ingress.
It's also not possible to have several ingress for one same LB/IP, so one can not route 50+ paths for a single domain.

As far as I can see, the issue seems to be that each `path` in the ingress spec is being translated to a GCP `PathRule` with a single path in it.

https://github.com/kubernetes/ingress-gce/blob/ee19757561cc5af9af3541a111eda702bf968a5c/pkg/controller/translator/translator.go#L209

https://github.com/kubernetes/ingress-gce/blob/b19360829ccff3c68da9bc0144eca6c2418241b9/pkg/loadbalancers/url_maps.go#L251

So it's easy to hit the max 50 [Path rules per path matcher quota](https://cloud.google.com/load-balancing/docs/quotas).

But several paths per `PathRule` seem to be supported by GCP:

https://github.com/kubernetes/ingress-gce/blob/e5b7444f083fd60e0d8d5106c0206cd8a2579bce/pkg/composite/gen.go#L1798-L1803

So if the controller somehow could manage packing several paths into a single `PathRule` the limit would not be so low.

Some options I can think of:

1. Allowing a space separated list of paths in the ingress `path` property

    ```
    paths:
    - path: '/posts /posts/* /es/posts/ /es/posts/* /de/posts/ /de/posts/*'
      backend:
        serviceName: post-service
        servicePort: 9876
    ```
    Then split them on the translation to UrlMap.

2. Grouping all the paths that point to a same backend under a single `PathRule`

    ```
    paths:
    - path: /posts
      backend:
        serviceName: post-service
        servicePort: 9876
    - path: /posts/*
      backend:
        serviceName: post-service
        servicePort: 9876
    - path: /es/posts
      backend:
        serviceName: post-service
        servicePort: 9876
    - path: /es/posts/*
      backend:
        serviceName: post-service
        servicePort: 9876
    - path: /tasks
      backend:
        serviceName: tasks-service
        servicePort: 5432
    ```

    Which would result in 

    ```
    $ gcloud compute url-maps describe someUrlMap
    hostRules:
    - ...
    kind: compute#urlMap
    name: ...
    pathMatchers:
    - defaultService: ...
    name: ...
    pathRules:
    - paths:
      - /tasks
      service: <tasks-service backend url>
    - paths:
      - /posts
      - /posts/*
      - /es/posts
      - /es/posts/*
      service: <post-service backend url>
    selfLink: ...
    ```

The first one would deviate more from the k8s ingress spec I guess, but I suppose
it is easier to implement and allows a more concise syntax, similar to the one already
used to create path-matchers with the gcloud command (see `--path-rules` option
in https://cloud.google.com/load-balancing/docs/url-map#path-matchers).

The second one would respect the current syntax for GCE Ingress resources, but
leaves less control to the user, and I guess would be harder to implement.

Sorry if these proposals are too naive somehow, I'm not familiar with the code.
If they make sense, I'd be willing to spend some time trying to put together a PR
with the solution considered more appropriate.
