### ISSUE TITLE
GKE is not creating Load Balancer automatically

### ISSUE THREAD

**Issue by dvaldivia** [kubernetes/ingress-gce#868]
I'm creating an ingress controller but no endpoint ip is getting assigned and the load balancer is not getting created, my question is how can I debug this? there doesn't seem to be an error shown anywhere, nor kubernetes nor gke console.

This ingress used to work, no idea why it stopped working, I've waited a few hours

ingress-app.yaml

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myapp-dev-ingress-http
  annotations:
    kubernetes.io/ingress.global-static-ip-name: myapp-dev
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    certmanager.k8s.io/acme-http01-edit-in-place: "true"
  labels:
    app: myapp-dev
spec:
  rules:
  - host: myapp.dev
    http:
      paths:
      - path: /api/
        backend:
          serviceName: my-service
          servicePort: 8000
  tls:
  - secretName: myapp-dev-tls
    hosts:
    - myapp.dev
```
